### ISSUE TITLE
talking to BT Net if Brand Soda is following you

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#109]

**Comment by funnyboy044** [comment]
show posty neutral
        show bs follow behind posty
        bs "Hello kind sir! I'm ready to sign any brand deals, contracts, or ambassadorships you put in front of me at a moment's notice!"
        btnet "Pardon?"
        p "We're looking for someone to market them."
        btnet "Aside from maybe a job at the museum, I'm afraid there's nothing I can do."
        p "Maybe you could give an object-on-the-street interview about them?"
        bs "Yeah, old man, give your honest thoughts!"
        btnet "Ummmmmm..."
        btnet "They make bad first impressions, expect rewards too quickly, has delusions of grandeur...
        btnet "Smells flat..."
        bs quiet "..."
        bs "We're leaving."
        p "Talk to you later!"
