### ISSUE TITLE
thing for Brand Soda to say to prevent you from leaving main street

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#11]
https://github.com/pixequil/oso-game-1/blob/3947b4363665b03f0ffaff9154071cda2a8d899b/game/room001-mainstreet.rpy#L43

**Comment by CONKINGTON** [comment]
"Ah sorry, we can't leave this place: 95% of the town has a restraining order against me for my promotional activities."

"Well, I guess you can't win them all!"

**Comment by pixequil** [comment]
@CONKINGTON please state how you want to be credited for writing contributions, or we can't accept this

**Comment by CONKINGTON** [comment]
Oh credit me as XKZ

> @CONKINGTON please state how you want to be credited for writing contributions, or we can't accept this
