### ISSUE TITLE
talking to Miso if Brand Soda is following you

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#110]
should be short! Brand Soda does not want to Miso for whatever reason. (this prevents there from needing to be 3 unique conversations)

**Comment by funnyboy044** [comment]
p "This guy seems like they'd be willing to invest in you."
bs "Ehhhhh...I don't know..."
bs "I've heard of this guy's parents. They're elitist art snobs."
bs "If I wanna be the next big thing and appeal to everyone, I can't just go to these big shots first."
bs "What if they don't like me and tell their friends how much I suck?"
bs "Let's pick someone less risky around here."
p "OK..."
miso "What are you guys talking about?"
p "Nothing!"
