### ISSUE TITLE
blue exhibit main painting conversation background with variations

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#113]
- [ ] museum_blue_p_rusty the painting is there, but it's behind rusted bars
- [ ] museum_blue_p_opened the bars are rusted even more, so they're gone and the painting can be taken
- [ ] museum_blue_p_missing the bars are still missing like the previous iteration, but now the painting is also gone.

**Comment by funnyboy044** [comment]
museum_blue_p_rusty
![blue1](https://github.com/pixequil/oso-game-1/assets/63936011/c63cd7b3-7404-40ae-845d-eccfc8713fea)

museum_blue_p_opened
![blue2](https://github.com/pixequil/oso-game-1/assets/63936011/dd9c08d5-567f-47b6-b985-e7e1dcad8f24)

museum_blue_p_missing
![blue3](https://github.com/pixequil/oso-game-1/assets/63936011/5a5a1951-c03f-460c-8357-8453cb96090a)
