### ISSUE TITLE
first conversation with Blue Tile

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#114]
Blue Tile explains their whole deal, while Posty is captured by the compulsion to take the painting

**Comment by CONKINGTON** [comment]
bt: My brain can't comprehend the composition of it all!!!
p: Ah yeah, I love how... orderly and serene it is.
p: (Here is the prize! Just need to wait for an opportunity)
bt: You said it!!! This exhibition makes me feel things like astonishment and awe and glory-
p: (That painting is so close to me, why can't he go away)
bt: Ever since these beautiful masterpieces fell from the clear skies, I always had to watch out for jealous vandals whom I won't name-
bt: _coughs_ Red Tile _coughs_
bt: who have a vendetta against this exquisite cultural array due to it being "the wrong colour".
bt: Personally, I don't have a particular favorite colour, I like all the colours of the rainbow: Blue, Zaffre, Periwinkle, Azure, Denim, Glaucous and Eclipse!
bt: But that doesn't mean I shun other colours like Mr "Paint the Whole Gallery" Red, I just like these pieces because of the message and the meaning behind every stroke and every frame...
p: (Damn this exhibition is putting me to sleep, maybe a splash of brown could perk this up)
p: Me too.
bt: I am so glad we can come to such total agreement about these pieces, not just because of colours!
p: Hahaha.

**Comment by pixequil** [comment]
I like blue tile's dialogue here, but taking the painting is not an explicit goal for Posty, at least not at the start of the scene, it's more of a spontaneous compulsion

**Comment by f4nimator** [comment]
```
label .painting:
    if saw.bluetile == False:
        show bg museum_blue_p_rusty
        show posty neutral
        show bluetile giddy
        $ saw.bluetile = True
        bluetile "Hello!! Another lover of this exhibit! Yay!!!"
        bluetile "This artwork in particular really speaks to me!! What about you?"
        p "Oh no I'm just looking aro-"
        show posty astonished anim
        "As soon as Posty glanced at the painting Blue Tile refered to, she was suddently captured by the compulsion to take it."
        p astonished "..Woahh..."
        bluetile "You said it!!! This exhibition makes me feel things like astonishment and awe and glory!"
        bluetile "Ever since these beautiful masterpieces fell from the clear skies, I always had to watch out for jealous vandals whom I won't name-"
        extend annoyed "{i} coughs Red Tile coughs{/i}"
        bluetile "who have a vendetta against this exquisite cultural array due to it being \"the wrong colour\"."
        p "Uh huh..."
        extend quiet "{i} If only those bars weren't in the way..{/i}"
        bluetile "Personally, I don't have a particular favorite colour, I like all the colours of the rainbow: Blue, Zaffre, Periwinkle, Azure, Denim, Glaucous and Eclipse!"
        bluetile "But that doesn't mean I shun other colours like Mr \"Paint the Whole Gallery\" Red, I just like these pieces because of the message and the meaning behind every stroke and every frame..."
        p "Yeah yeah.."
        extend quiet "{i} How would I even carry it?{/i}"
        bluetile "I am so glad we can come to such total agreement about these pieces, not just because of colours LIKE SOMEONE WHO I HAVE THE GRACE TO NOT NAME AND SHAME!"
        #114
        if item.ladle_full:
            jump .painting_ladle_blocked
        else:
            p neutral "Huh- Oh I should probably go. Cya!"
            jump museum_blue
```

**Comment by funnyboy044** [comment]
label .painting:
    if saw.bluetile == False:
        show bg museum_blue_p_rusty
        show posty neutral
        show bluetile giddy
        $ saw.bluetile = True
        bluetile "Hello!!! Another lover of this exhibit! Yay!!!"
        bluetile "I'm Blue Tile! My friends call me Blue! That's my friend Red Tile! Who are you?"
        p "Name's Posty. What's going on?"
        p "This is the new blue exhibit they curated just a few days ago! This is the one of the happiest days in my life!"
        bluetile "This artwork in particular really speaks to me! It's a portrait of Crayon Box, the host of that reality show in the dome! What about you?"
        p "Oh no, I'm just looking aro-"
        posty astonished anim "!"
        "As soon as you clance at the painting Blue Tile refered to, you are suddently raptured with the feeling of {color=#ffff00}{i}inspiration{/i}{/color}."
        p astonished -anim "...Woahh..."
        bluetile "You said it!!! This entire exhibition makes me feel things like astonishment and awe and glory!"
        bluetile "Ever since these beautiful masterpieces fell from the clear skies, I always had to watch out for jealous vandals whom I won't name-"
        extend annoyed "{i}coughs{/i} Red Tile {i}coughs{/i}"
        bluetile "who have a vendetta against this exquisite cultural array due to it being \"the wrong colour\"."
        p "Uh huh..."
        extend quiet "{i} If only those bars weren't in the way...{/i}"
        bluetile "Personally, I don't have a particular favorite colour, I like all the colours of the rainbow: Blue, Zaffre, Periwinkle, Azure, Denim, Glaucous and Eclipse!"
        bluetile "But that doesn't mean I shun other colours like \"Mr Paint the Whole Gallery Red\", I just like these pieces because of the message and the meaning behind every stroke and every frame..."
        p "Yeah yeah..."
        extend quiet "{i} How would I even carry it?{/i}"
        bluetile "I am so glad we can come to such total agreement about these pieces, not just because of colours LIKE SOMEONE WHO I HAVE THE GRACE TO NOT NAME AND SHAME!"
        if item.ladle_full:
            p astonished "SCREW IT! I HAVE TO SET IT FREE!"
            jump .painting_ladle_blocked
        else:
        bluetile scared "Are you doing OK?
        show posty neutral
        p "Huh- Oh! I'm sorry! I think dozed off there."
        bluetile giddy "Oh, that's alright! I get that way sometimes when I stand here for too long."
        p "I should probably go. Cya!"
            jump museum_blue
