### ISSUE TITLE
red tile offers to distract blue tile in exchange for the red cash 

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#118]
(and because they want that painting harmed)

**Comment by CONKINGTON** [comment]
p: Hey Red, can I ask you a favour?
rt: Sure, whatcha want me to do?
p: I attempted to "add" some colour to the exhibition, but Bluey here stopped me.
rt: Ah of course, Blue would never let his precious little pieces get harmed.
p: Well, I noticed that the guy gets really passionate when it comes to blue stuff, so I was hoping you could distract him with a couple of remarks.
rt: No way.
p: Come on, you can get revenge for the Red Exhibit, just some small talk.
rt: When it comes to the colour blue, it is never small talk.
rt: That guy can be so hung up on that it is annoying.
rt: One more hour of him whining and I am leaving.
p: What would it take?
rt: Some cash; if I have to deal with him, at least I should be fairly compensated
