### ISSUE TITLE
conversation where Brand Soda decides to follow you

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#12]
https://github.com/pixequil/oso-game-1/blob/3947b4363665b03f0ffaff9154071cda2a8d899b/game/room001-mainstreet.rpy#L88

**Comment by PlugBoyOfficial** [comment]
i cant upload any files but here's the scene i wrote

p "Hey, BS!"

    bs "Yo, Posty! How’s my favorite mailbox?"

    p "I’m doing alright..I got a big package to deliver today!"

    bs "Dope. What’s it for?"

    p "Just the OSO dome, is all."

    bs "WOAH! That {i}is{/i} big! Something like that is bound to draw a lot of attention…"

    bs "Do you have any idea how overwhelming that could be?"

    p "Oh, uh… I never thought about it that way."

    bs "Don’t worry, bud, I got your back."

    show bs follow with move:
        xalign 0.35

    bs "While you deliver the package, I’ll direct those prowing eyes towards yours truly!"

    bs "Get some brand deals, maybe sign a deal or two…Everybody wins!"

    p "Alright, I guess. The more the merrier, right?"

    bs "Sweet!"

**Comment by pixequil** [comment]
@PlugBoyOfficial this doesn't work in the context of brand soda's character. brand soda is largely unpopular and is banned from all areas other than main street

**Comment by funnyboy044** [comment]
Modified version of Plugboy's dialogue that fits in with his established characterization
   
    $ last.mainx = 1.0
    scene bg mainstreet
    show posty neutral
    show bs behind posty

    bs "Yo, Posty! How’s my favorite mailbox?"
    p "Oh, hi Brand Soda. I'm busy with delivering an important package right now."
    bs "Dope. Who’s it for?"
    p "The OSO Dome."
    bs "WOAH! That...is...big! Something like that is bound to draw a lot of attention…"
    bs "Do you have any idea how overwhelming that could be?"
    p "It kinda slipped past me..."
    p "Hey speaking of attention, how's that deal at the comedy club?"
    bs "They banned me after one act, can you believe it? Called me a hack fraud."
    bs "ME! THE NEXT BIG THING!"
    p "What did you do to get banned?"
    bs "I called the audience freaks and geeks for about ten minutes."
    bs "The whole street banned me actually."
    bs "Even if I took one step on the pavement there, they'd call the police on me for trespassing."
    bs "And other streets caught wind and now I can't promote myself anywhere else other than here."
    p "Dang...that sucks dude."
    bs "If I had a marketing agent or something, I could get enough attention on me to get back into those venues..."
    bs "Hey, I have an idea! What if you took me around town and we can get some marketing for me?"
    p "Oh, I don't know...I've got a lot on my plate right n-"

    show bs follow with move:
        xalign 0.35
    
    bs "Nope, it's already decided. I'm here now!"

    $ party_bs = True
    "{b}{color=#df7dff}Brand Soda{/color}{/b} joined your party!"

    p "Alright, I guess."
    bs "Sweet! Let's get us some marketing!"

**Comment by pixequil** [comment]
looks good!
