### ISSUE TITLE
scene where posty, alone, splashes miso soup on the painting 

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#121]
and takes the painting on impulse now that the bars are rusted away. blue tile shows up, too late, and is upset about it.

**Comment by CONKINGTON** [comment]
p: Aighty, here it goes!
*splash*
p: Drat, I missed-
bt: Hey! Whatcha doing to that gate?!
p: What gate-
p: Ohhhh.
bt: You better step away from here as soon as possible or you will be stuffed with legalese!
p: Welll I am sorry for this incident, I will leave here soon...
p: But first, I'll get a little something!
*You have obtained the painting!*
bt: COME BACK HERE YOU BARBARIC PATCH OF SCRAP, THAT AIN'T YOURS TO TAKE!
p: Well as much as I loveeeee listening to you drone and deny your denimy desire, I mustn't dally for long!
p: Toodles!

**Comment by pixequil** [comment]
It's good but I can't remember if other scenes rely on blue square not having seen you take it

**Comment by CONKINGTON** [comment]
From what you said, it appears that Blue Square sees the miso soup on the gate and draws the conclusion you splashed it.

**Comment by pixequil** [comment]
I'm sorry for being unclear. I think blue tile doesn't know who did it

**Comment by CONKINGTON** [comment]
p: Aighty, here it goes!
splash
p: Drat, I missed.
p: All I hit was this gate that has rusted open-
p: ...
p: I just have a little idea.
_You have obtained the painting!_
p: Ohohoho I can't wait to see Bluey's face!
_dashes away_
bt: I swear I have never seen a more unqualified person in my life; he can't appreciate their subtle nuances-
bt: ...
bt: Where did the painting go?
bt: This exhibit has been... vandalized
bt: My piece, gone.
bt: Who did this?
bt: Who dared to lay their fingertips on this masterpiece??
bt: I'll find that thief and stuff them with so much legalese they will be speaking it.
bt: DO YOU KNOW WHO I AM?!
bt: I HAVE A WHOLE BOOK OF LAWYERS READY TO LITIGATE YOUR EXISTENCE, CAN YOU HEAR ME?!
bt: I swear if that piece doesn't comeback here with thirty minutes I'll send the dogs out.
bt: Aaaaaaaaaaaaaarggh
