### ISSUE TITLE
blue exhibit main painting on display

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#122]

**Comment by pixequil** [comment]
@funnyboy044

**Comment by funnyboy044** [comment]
Asset: https://drive.google.com/file/d/1U93IOK3O-aqY116xnPutc_-SaiRzJn0J/view?usp=sharing
image below is resized to 291 x 404 px
![blue_exhibit_main_painting_resized](https://github.com/pixequil/oso-game-1/assets/63936011/984a74ac-5228-49b7-b22a-27dcfa9bdf45)
credit to Vio!
