### ISSUE TITLE
revisiting blue tile casually before anything happens

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#123]

**Comment by funnyboy044** [comment]
elif saw.bluetile and (item.ladle_full == False):
        show bg museum_blue_p_rusty
        show posty happy
        show bluetile giddy
        p "Hey again, Blue!"
        bluetile "Hi Posty!"
        show posty concerned
        "You look away from the painting. You don't want to be caught in a trance again. You can sense the {color=#ffff00}{i}inspiration{/i}{/color} emanating from the framed piece."
        p "So what's so great about this piece?"
        bluetile "Isn't it obvious?"
        p suspicious "Well like, is it the imagery and subject matter people make with the color blue?"
        p "I mean, with this piece, Crayon Box is something of a pop art icon nowadays."
        bluetile "Oh of course! What people create with the lightest tints of cyan and an analogous color palette is incredible!"
        bluetile annoyed "My friend Red likes to think that all I am is a numbnuts obsessed with the color blue, like I'm its number one fan and sworn protector."
        p "Aren't you though?"
        bluetile giddy "Well yeah!"
        bluetile "But what they don't know is that I wouldn't be if everything blue wasn't so pretty!"
        p "OK."
        p "Well, talk to you later."
        bluetile giddy "Bye Posty! Come by again!"
        jump museum_blue
