### ISSUE TITLE
blue tile after the painting is stolen 

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#125]
(still doesn't know posty did it)

**Comment by CONKINGTON** [comment]
p: What is wrong, feeling blue?
bt: It's the painting, it is gone!
p: Oh whaat nooo, you know where it went?
bt: God dammit no! I WOULDN'T BE LOOKING AROUND FOR IT IF I HAD IT!
p: Damn calm down dude, think where you last seen it and work backwards from there.
p: That is what I do when I lose my extremely valuable possessions.
bt: Ooohh it is that crimson red fucker who took my precious painting : that asshole was never open to anything that didn't rhyme with zred or mrimson! 
p: language
bt: I was always accommodating to his wishes and desires about the place; hell I was considering adding a red piece to even it out.
bt: But Reddy ol' Red Red just went and declared war on me! That won't stand on my watch.
p: good luck with the painting

**Comment by pixequil** [comment]
It's funny overall, although the word philistine may be offensive and should be replaced

**Comment by CONKINGTON** [comment]
Changed it to ignoramus

**Comment by CONKINGTON** [comment]
p concerned: What is wrong, feeling blue?
bt scared: It's the painting, it is gone!
p sad: Oh whaat nooo, you know where it went?
bt scared: God dammit no! I WOULDN'T BE LOOKING AROUND FOR IT IF I HAD IT!
p confused: Damn calm down dude, think where you last seen it and work backwards from there.
p: That is what I do when I lose my extremely valuable possessions.
bt annoyed: Ooohh it is that maroon loser who took my precious painting : that cultural ignoramus was never open to anything that didn't rhyme with zred or mrimson!
p concerned: language
bt annoyed: I was always accommodating to his wishes and desires about the place; hell I was considering adding a red piece to even it out.
bt annoyed: But the scarlet boor just went and declared war on me! That won't stand on my watch.
p concerned: anyway good luck with the painting

**Comment by CONKINGTON** [comment]
```
p concerned "What is wrong, feeling blue?"
bt scared "It's the painting, it is gone!"
p sad "Oh whaat nooo, you know where it went?"
bt "God dammit no! I WOULDN'T BE LOOKING AROUND FOR IT IF I HAD IT!"
p confused "Damn calm down dude, think where you last seen it and work backwards from there."
p "That is what I do when I lose my extremely valuable possessions."
bt annoyed "Ooohh it is that maroon loser who took my precious painting : that cultural ignoramus was never open to anything" that didn't rhyme with zred or mrimson!
p concerned "language"
bt annoyed "I was always accommodating to his wishes and desires about the place; hell I was considering adding a red piece to even it out."
bt "But the scarlet boor just went and declared war on me! That won't stand on my watch."
p "anyway good luck with the painting"
```

**Comment by pixequil** [comment]
Instead of having it start with Posty neutral and immediately change to concerned, the declaration should change to say concerned. I know all the declarations say neutral but that's because the code breaks if there's no expression in the skeleton

**Comment by CONKINGTON** [comment]
```
elif quest.painting_blue:
show bg museum_blue_p_missing
show posty concerned
show bluetile scared
p "What is wrong, feeling blue?"
bt scared "It's the painting, it is gone!"
p sad "Oh whaat nooo, you know where it went?"
bt "God dammit no! I WOULDN'T BE LOOKING AROUND FOR IT IF I HAD IT!"
p confused "Damn calm down dude, think where you last seen it and work backwards from there."
p "That is what I do when I lose my extremely valuable possessions."
bt annoyed "Ooohh it is that maroon loser who took my precious painting : that cultural ignoramus was never open to anything that didn't rhyme with zred or mrimson!
p concerned "language"
bt annoyed "I was always accommodating to his wishes and desires about the place; hell I was considering adding a red piece to even it out."
bt "But the scarlet boor just went and declared war on me! That won't stand on my watch."
p "anyway good luck with the painting"
jump museum_blue
```
