### ISSUE TITLE
red tile after you steal the painting

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#126]

**Comment by CONKINGTON** [comment]
rt: You got the painting?
p: Yep, feels more satisfying than expected.
rt: Now you understand why I feel the way I feel about him.
p: I think I forgot what blue means.
rt: B.T has that effect on people: too much time in his company and you begin to loathe that spectrum.
rt: From what I heard, he is a bit peeved about me.
rt: I would refrain from talking to him about this matter...

**Comment by f4nimator** [comment]
```
    if quest.painting_blue:
        show posty neutral
        show redtile
        p "You know how Blue Tile is always obsessed with the blue exhibit?"
        redtile "Uh huh."
        p "And how he goes absolutely ballistic if you even touch them wrong?"
        redtile "Yeah, tell me about it! I can't even touch them for April Fools!!"
        p happy "I got one of them."
        $ renpy.transition(hpunch, layer="master")
        redtile "WHAT?!"
        p "I have one of the blue paintings."
        redtile "Y-You have one of them?! One of the things that gets Bluey in a twist?"
        p suspicious "Why did you think I paid you to argue with the guy? I ain't exactly invisible so I needed a distraction."
        redtile "I thought you were going to do a small prank like splash the paintings a bit or flip them upside down, not straight up robbing the place!"
        p happy "As Piquante once said: good artists copy, great artists steal!"
        redtile "He didn't mean {i}literally{/i} stealing anything! It was a metaphor for making your ideas your own-"
        p "Sorry to interrupt your art lecture, but I got whatever the opposite of a fait accompli is to make."
        p "Enjoy the cash!" #126
        jump museum_blue
```

**Comment by funnyboy044** [comment]
I added on to f4nimator's dialogue a little bit

    elif item.ladle_full:
        show posty neutral
        show redtile
        redtile "How it'd go?"
        p happy "Perfect! I missed the painting and completely melted the fence."
        redtile "That sounds like you failed."
        p "Well actually, you know how Blue Tile is always obsessed with the blue exhibit?"
        redtile "Uh huh."
        p "And how he goes absolutely ballistic if you even touch them wrong?"
        redtile "Yeah, what about it?"
        p happy "I got one of them."
        $ renpy.transition(hpunch, layer="master")
        redtile "WHAT?!"
        p "I have one of the blue paintings."
        redtile "Y-You have one of them?! One of the things that gets Bluey in a twist?"
        p suspicious "Why did you think I paid you to argue with the guy? I ain't exactly invisible, so I needed a distraction."
        redtile "I thought you were going to splash the paintings, not straight up rob the place!"
        p happy "As Piquante once said: good artists copy, great artists steal!"
        redtile "He didn't mean {i}literally{/i} stealing anything! It was a metaphor for making your ideas your own-"
        p "Yeah yeah, \"the opposite of a fait accompli is to make.\" I got it!"
        redtile "You're a criminal, Posty! But so am I. I'm sure we can agree not to rat each other out?"
        p "Oh totally!"
        redtile "Great. Thanks again by the way!"
        redtile "Y'know, for helping me with my revenge."
        p "Enjoy the cash!" #126
        jump museum_blue
