### ISSUE TITLE
talking to security cameron after splashing soup on the painting

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#128]

**Comment by funnyboy044** [comment]
p "Security Cameron! Some vandal stole a painting in the blue exhibit!"
        cameron "While I'm standing here? I doubt that."
        p "No seriously! It's gone!"
        cameron "Really?"
        hide cameron
        p "I hope this gets suspicion off of me."
        show cameron
        cameron "Someone did steal this! No one is allowed off the premises!"
        cameron "Except you, Posty!"
