### ISSUE TITLE
brand soda hint

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#13]
```
        yd "hint for if Brand Soda is following you" # TODO: brand soda hint
```

https://github.com/pixequil/oso-game-1/blob/c9953ec3e6480bd1dfa989c34c13f39644383997/game/toasty_hints.rpy#L15-L19

**Comment by xbeo01** [comment]
```py
bs "Hello!"
t "Who is this you brought along to follow you?"
p "Oh, we are looking for someone to wants to advertise."
t "Well that surely isn't me; I don't care."
bs "..."
t "Maybe try talking to that guy beside the Music Shop" # i forgot how to bold text lol
p "Oh, that sounds like a good idea!"
t "That will be $100 for my hint."
p "..."
```

**Comment by pixequil** [comment]
toasty should never acknowledge that these are hints. also for this one i think it's best for toasty to simply urge you to talk to everyone you see until someone finally takes brand soda. it's not that difficult because you're not allowed to leave the area

**Comment by funnyboy044** [comment]
bs "Hello!"
t smug "Who is this you brought along to follow you?"
bs "Lady, I'm gonna be the next big thing!"
p happy "We're looking for someone who wants to advertise them."
t annoyed "Well that surely isn't me; I don't care."
show posty neutral
bs "Oh..."
t smug2 "Try talking to somebody else around here. No one loiters around Main Street unless they've got a few dollars to burn."
bs "Oh, that sounds like a good idea!"
t smug5 "Good idea? Aimlessly walking around and talking to strangers?"
show toasty pointandlaugh talk
p angry quiet "..."

**Comment by funnyboy044** [comment]
@pixequil

**Comment by pixequil** [comment]
i love it
