### ISSUE TITLE
red tile refuses to use the ladle a second time, urging posty to do it

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#130]

**Comment by funnyboy044** [comment]
elif item.ladle_full:
        show posty astonished
        show redtile
        redtile "What are you still doing with that ladle, Posty?"
        p "I filled it with miso soup again!"
        redtile "What? What happened to \"get it as far away from here as you can?\""
        p "It's complicated! Look, you have to take this ladle back!"
        show ladle_full
        p "You need to splash the soup on the painting! You have to do it for me!"
        redtile "Posty, I gotta go on living!"
        p "Just throw it! Throw it when no one's looking!"
        redtile "You throw it when no one's looking!"
        p "I can't! I'm not sneaky! They'll send me to jail and I can't afford bail on a post office salary! Please, you gotta do it for me, I'm begging you!"
        redtile "Nothing doing! I can't be seen with the ladle! I'm trying to lay low! It has to be you!"
        show posty concerned
        p concerned "OK, I guess I'll do it myself."
        p angry "But I get arrested for this..."
        extend "I'll be really upset with you."
        hide ladle_full
        jump museum_blue
