### ISSUE TITLE
ahiss mini sprite

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#135]
![ahiss_close](https://github.com/pixequil/oso-game-1/assets/99515471/8e222a79-fedc-4db9-bb7d-a8cf982f78c2)
![ahiss_open](https://github.com/pixequil/oso-game-1/assets/99515471/46a0a3cd-54f0-493c-bb0c-c2dcb85b97e3)

**Comment by funnyboy044** [comment]
Asset: https://drive.google.com/file/d/1tsE5hxjqqa-ydKwBLFrUDCA348s5eY5A/view?usp=sharing
Credit: monologueslog
![ahiss_the_Cat_transparent](https://github.com/pixequil/oso-game-1/assets/63936011/ff3e92c7-c157-4ebb-a133-c28d534449fb)
