### ISSUE TITLE
rose colored glasses mini sprite

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#136]
![rcg_close](https://github.com/pixequil/oso-game-1/assets/99515471/a3cb1d04-10b9-4bc9-a904-5215175fe5e2)
![rcg_open](https://github.com/pixequil/oso-game-1/assets/99515471/94643fc5-c3b7-4caa-ae13-0467e541458f)

**Comment by funnyboy044** [comment]
Credit: Stray
Asset: https://drive.google.com/file/d/1T2bGDu_p6R37GM3P0YRS7nE0WTiTIYvX/view?usp=sharing
![oso-game-rose-colored-glasses-angry-sprite](https://github.com/pixequil/oso-game-1/assets/63936011/aa6d3bd7-98c2-402b-8bbb-31ef2008c0f8)
