### ISSUE TITLE
marble bust talksprites

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#137]
![fffffffffffmarble_final](https://github.com/pixequil/oso-game-1/assets/99515471/dac80480-2ac9-433e-88fc-694ff27e0128)

**Comment by funnyboy044** [comment]
Asset: https://drive.google.com/file/d/1B6WsD88DJTdGrQ6VC_pIGlr11sTsnEHk/view?usp=sharing
https://drive.google.com/file/d/1GqCp2v4WwNRMf6fVBfEq-VHpAEjeTLEu/view?usp=sharing

Credit: multi
