### ISSUE TITLE
notepad talk sprites

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#138]
![notepad (1)](https://github.com/pixequil/oso-game-1/assets/99515471/2e975e38-2864-4ef4-93dc-260fa3495a54)

**Comment by funnyboy044** [comment]
Asset: https://drive.google.com/file/d/1Oo8RRnQ8XQ3HGnUJFlIHn5QstaHsMYY7/view?usp=sharing

Credit: Fluffystar_XD

**Comment by funnyboy044** [comment]
close when implemented
