### ISSUE TITLE
ripped mitten talksprites

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#139]
![ripped_mitten_alpha](https://github.com/pixequil/oso-game-1/assets/99515471/879314eb-a7f9-405e-8611-7edba7db7d7f)

**Comment by funnyboy044** [comment]
Credit: NovaInterstellations
![ripped_mitten_idle](https://github.com/pixequil/oso-game-1/assets/63936011/070bd46c-836b-469a-b4dc-b283db9b94ea)
![ripped_mitten_close](https://github.com/pixequil/oso-game-1/assets/63936011/6101f6c1-86b6-497b-ae9b-bf82857da090)
![ripped_mitten_open](https://github.com/pixequil/oso-game-1/assets/63936011/531ec6f1-8dea-4bdf-9b2a-3a4504174d0b)
