### ISSUE TITLE
squirt bottle talksprites

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#140]
![squirtbottle](https://github.com/pixequil/oso-game-1/assets/99515471/e8114c90-388d-47ea-900f-6ba780ff1a49)

**Comment by funnyboy044** [comment]
Assets:
https://drive.google.com/file/d/1wC3yu1jJEoQhG91l2io0BaPCZO2EwiBo/view?usp=sharing
https://drive.google.com/file/d/1vfu7adJKJsdLyBtGA0Mtc8_3w6aurVmW/view?usp=sharing
Credit: 4DJumpman256
