### ISSUE TITLE
stick shift talksprites

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#141]
![stick_shift](https://github.com/pixequil/oso-game-1/assets/99515471/b47f9316-881e-43c9-b7d5-027588641ee7)

**Comment by funnyboy044** [comment]
Assets: https://drive.google.com/file/d/1JJPRjWgh8OLX-fvZybJvQXBY_B7pCyG4/view?usp=sharing
https://drive.google.com/file/d/1zp2U_NnZjix4sfR0wI94dL55ngNNEhA1/view?usp=sharing

Credit: Tempøral Løser

implement
