### ISSUE TITLE
tag talksprites

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#142]
![Tag_overworld](https://github.com/pixequil/oso-game-1/assets/99515471/dfacf2d8-1974-4db0-bc82-dc74550a3074)
![image](https://github.com/pixequil/oso-game-1/assets/99515471/92342924-0209-41f0-851e-bb52c1db0a4f)

**Comment by funnyboy044** [comment]
Link to Sprites: https://drive.google.com/file/d/1_gBO8Dl_Om2hxb20uLAEHac8-VgSQZ9K/view?usp=sharing

Credit to gomigg.

^ implement this
