### ISSUE TITLE
war exhibit conversation background

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#149]
![image](https://github.com/pixequil/oso-game-1/assets/99515471/ff3fec77-ed12-4f61-98d1-8e8bdf5046ba)

**Comment by pixequil** [comment]
should be in front of a blank wall, so that different paintings can be featured behind the different conversations and interacted with

**Comment by pixequil** [comment]
![image](https://github.com/pixequil/oso-game-1/assets/99515471/bb699d58-d1f6-4714-be2e-b73264d41e2d)
rough layout of how it should look

**Comment by funnyboy044** [comment]
Credit to: Cleft Key

Variation 1: Original Background w/ painting
![war_exhibit_dbg_1](https://github.com/pixequil/oso-game-1/assets/63936011/73ddcc3e-fd9b-432c-baf5-3bfedf2373a6)

Variation 2: Background w/ no painting
![war_exhibit_dbg_2](https://github.com/pixequil/oso-game-1/assets/63936011/346f9f05-4c25-44bf-a25e-47cc2e992119)

Variation 3: Background w/ green painting (needed for puzzle)
![war_exhibit_dbg_3](https://github.com/pixequil/oso-game-1/assets/63936011/f89c6fd2-6f58-44f2-9675-dce9b6bb101b)

Variation 4-6: Background w/ other colors of the painting (blue, red, inverted colors)
![war_exhibit_dbg_4](https://github.com/pixequil/oso-game-1/assets/63936011/1a2b1a09-5bc2-410b-b8be-a0b20e5e24bc)
![war_exhibit_dbg_5](https://github.com/pixequil/oso-game-1/assets/63936011/fcf1f095-e3fa-4aef-b5ae-7f1bcbc11913)
![war_exhibit_dbg_6](https://github.com/pixequil/oso-game-1/assets/63936011/cf5c7e6a-06c3-40c4-97bc-3ddd54b049d7)
