### ISSUE TITLE
"heavier" item art

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#151]
It's the opposite of a lighter. Instead of adding fire to things, it removes fire from things. It has to look pretty heavy. There is no reference art for this made-up tool, but, I think it should look like it functions in an analog way, like a lighter would. That is, it's nothing high-tech. Very much open to interpretation.

**Comment by Martysh12** [comment]
you know it kinda reminds me of a fire extinguisher

**Comment by pixequil** [comment]
maybe, but its function is a lot cleaner than a fire extinguisher. it doesn't 'put out' the fire, it removes the fire.

**Comment by pixequil** [comment]
still, a fire extinguisher might be a good starting point for inspiration.

**Comment by Martysh12** [comment]
yes, considering fire extinguishers are known for being heavy

**Comment by funnyboy044** [comment]
Asset: https://drive.google.com/file/d/16fXVPRtgVonW-xMWhidnxbGKivouCv8s/view?usp=sharing
Credit: XKZ
![Heavier](https://github.com/pixequil/oso-game-1/assets/63936011/7cc828ef-6099-4a9d-8c68-10b50b27ee66)
