### ISSUE TITLE
full-size fire burger painting (and fire-free version)

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#156]
![burger_fire](https://github.com/pixequil/oso-game-1/assets/99515471/c4a56b30-69b0-491a-8dfa-a577daa750d5)
![burger_out](https://github.com/pixequil/oso-game-1/assets/99515471/3bae558b-bc9f-4336-864f-344a1681d168)

**Comment by funnyboy044** [comment]
![big_fire_painting_2](https://github.com/pixequil/oso-game-1/assets/63936011/2ccc8968-4d59-482a-86d0-842e3a41ef28)
![big_fire_painting_1](https://github.com/pixequil/oso-game-1/assets/63936011/acbc5787-d273-4573-a141-e2335f56202d)
Asset: https://drive.google.com/file/d/1PX2HGOLi9kl7mZJeykC-RV0OdLfaai7J/view?usp=drive_link
https://drive.google.com/file/d/1PX2HGOLi9kl7mZJeykC-RV0OdLfaai7J/view?usp=drive_link
Credit to: Thotrike
