### ISSUE TITLE
imaginary lighter item

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#158]
it's like a lighter but imaginary

**Comment by funnyboy044** [comment]
Asset: 
![Imaginary_Lighter](https://github.com/pixequil/oso-game-1/assets/63936011/edceb158-b241-4ee3-bd95-ce26866d448d)
https://drive.google.com/file/d/1-5B224Fn2i0w3aU1cGTpfQiY6fO57Yyi/view?usp=sharing

**Comment by funnyboy044** [comment]
Do we need to wait until after we implement the asset to close the issue?

**Comment by funnyboy044** [comment]
Credit: cherryberry24 / Sparkle Spark
