### ISSUE TITLE
imaginary lighter description

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#159]
the imaginary lighter can be used to add fire to imaginary things.

**Comment by CONKINGTON** [comment]
Lighter? What lighter?

**Comment by pixequil** [comment]
description needs to say what it does

**Comment by pixequil** [comment]
this description idea can be considered based on whether the scene's dialogue ends up describing what the item does

**Comment by pixequil** [comment]
assigned to Crookie
