### ISSUE TITLE
conversation where posty convinces yd to support Brand Soda. Brand Soda, grateful, gives Posty some money as thanks.

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#16]
https://github.com/pixequil/oso-game-1/blob/bda13de7f02e91e6fd348a40107169783d0e5c67/game/room001-mainstreet.rpy#L120

**Comment by pixequil** [comment]
https://github.com/pixequil/oso-game-1/blob/c9953ec3e6480bd1dfa989c34c13f39644383997/game/room001-mainstreet.rpy#L119-L141

**Comment by funnyboy044** [comment]
yd "Hi Maily!"
    p "Posty."
    yd "Hi Posty! Hi Soday!"
    p happy "Hi Yellow Diamond. Say guess what, I have this friend you might be interested in!"
    bs "Hello strange child! Are you in need of a comedian, spokesperson, or hypeman?"
    yd "No!"
    bs "Oh ok then."
    yd "I just need a best friend to promote my flying lessons start-up! But I haven't found anyone yet! I'm sad!"
    bs "PR work, huh?"
    p happy "It's your angle, man! Go for it!"
    bs "Say, um, yellow diamondy boy, what would you need for this best friend role?"
    yd "I need them to market my business oppurtunity! They would be the face of the company while I do all the important stuff!"
    bs "Hey, I can be that!"
    yd "They need to be very charismatic! Are you charismatic?"
    bs "I have tons of charisma coming out of my butt!"
    yd "HAHAHA! You're funny!"
    yd "Are you smart at buahs-ness?"
    bs "Oh totally! I have experience all over the city!"
    bs "In fact, the city thinks I'm too forward thinking for the citizens of this town."
    bs "So now, I'm stuck on this street without a single penny or crumb to my name..."
    yd "Oh no!"
    bs "Yes, it's quite tragic..."
    bs "But you know, now I have all the time in the world and am completely available except on Tuesdays!"
    bs "Say, is it possible that this gig could be famous?"
    yd "Exactly! I am very confident it could go national!"
    bs "National marketing...wow..."
    p "Oh yeah, trust me! This yellow guy's a real visionary!"
    bs "Oh sign me up! I am totally in on this!"
    yd "Yay!"
    yd "Oh, one more thing! Very important!"
    yd "Do you like nachos?"
    bs "Pffftt...I'm a nachoholic!"
    bs "I like to put everything on them!"
    yd "Wowzers! Me too!"
    yd "Is this a beginning of a beautiful friendship?"
    bs "Oh, more than that! We became best buds!"
    yd "YAYYYYYY!"

[**Brand Soda** left your party!]

    bs "Posty! Thanks to you, I'm employed! I can't thank you enough!"
    bs "Just to show you I'm not the heartless celebrity that everyone thinks I am, here's a bonus for helping me find a marketing agent and way back into the spotlight!"

[**Brand Soda** gave you some money!]

    p happy "Wow, thanks Brand Soda!"
    bs "I'll never forget you!"
    bs "So kid, what is this buisness oppurtunity you were starting again?"
