### ISSUE TITLE
hint for if you have the heavier

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#162]

**Comment by CONKINGTON** [comment]
show toasty crossedarms
show posty concerned
t "What's up-"
p " So. Heavy."
t neutral "Posty are you alright?"
p "I have been carrying this heavier."
t annoyed "What the hell is a heavier?"
p "It apparently *pant* sucks fire in."
t "Really? You have really sunk in your lies."
p "I *pant* swear. It hurts..."
t smug "Yadda yadda we get it, you are weak"
t "Let me handle it."
"Toasty has the heavier!"
t annoyed "DAMN *pant* HOW DID *pant* YOU CARRY *pant* THIS?!"
p astonished "I don't know?! Probably willpower or *pant* something like that."
t "Well *pant* I need *pant* consultation pronto."
t turned "oh boy."
t "This is a pretty awkward situation *pant* I have gotten myself in *pant* ToastMaestro!"
t "Well Mailmouth did say *pant* this thing can suck fire up!"
t "So we need to find *pant* some fire *pant* to suck up!"
t "There  was a *pant* painting *pant* that has *pant* some fire. *pant* in the gallery."
t "Yeah *pant* that'll *work*."
t "Let's give this *pant* back."
t annoyed "Here *pant* you go."
"You have received the heavier!"
t "Don't do that to me ever again."
