### ISSUE TITLE
champurrlain painting

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#166]
> a painting of a famous war general (Champurrlain)

on the map the painting looks like this? which is confusing because it doesn't seem to be depicting a war general at all. feel free to just ignore this thing and make something completely different; if this weird banner needs to be changed then it'll be reused elsewhere.
![image](https://github.com/pixequil/oso-game-1/assets/99515471/0ea8462f-aff5-44dd-a6aa-b3504654ea82)

should loosely resemble Ahiss the Cat (below) but not look like they're especially related. i think if it's making the same pose, that could be funny, but it's not a requirement.
![image](https://github.com/pixequil/oso-game-1/assets/99515471/caebe466-70d0-4558-82e4-f08b796c01e8)

**Comment by funnyboy044** [comment]
Asset: https://drive.google.com/file/d/1UCGoQUT3BbEaJDhHW4Z-v8EWD-DFI4sO/view?usp=sharing
![Champurrlain_painting](https://github.com/pixequil/oso-game-1/assets/63936011/c009941e-6a95-43f4-aa62-8aebe4ff4e92)
credit to nexty
