### ISSUE TITLE
battery closeup

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#168]
![image](https://github.com/pixequil/oso-game-1/assets/99515471/5300ae0d-800f-48eb-926e-b2df890aa61b)

**Comment by funnyboy044** [comment]
Assets:
- https://drive.google.com/file/d/1fqTSktk1mSnuGeYVef-Cxt9UdUAkwRpa/view?usp=sharing
- https://drive.google.com/file/d/1jZpXKK20rdcqCRmjCs0g9_KSn8nyzgnf/view?usp=sharing

Credit: EliTaken

![Battery](https://github.com/pixequil/oso-game-1/assets/63936011/625bd29f-e926-415b-b30c-992983bf2843)
![batteries](https://github.com/pixequil/oso-game-1/assets/63936011/7daf571b-9892-4c1b-bade-8611afff7a87)
