### ISSUE TITLE
version of museum_war_top.png without battery and deed

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#169]
as these are both interactible removable items, but they're currently baked into the art, there needs to be a version of this map without them on the floor. im not tagging this as art because it's more like cleaning? i might do this myself in the end
![museum_war_top](https://github.com/pixequil/oso-game-1/assets/99515471/57cbf426-95d4-4273-826c-65015031df55)

**Comment by Martysh12** [comment]
can i do this

**Comment by funnyboy044** [comment]
if you get to it before either of us do, then go ahead

> can i do this

**Comment by Martysh12** [comment]
![museum_war_top_no_bat](https://github.com/pixequil/oso-game-1/assets/49569238/79d21c3c-bb0d-49b4-a0f1-308c25b40102)
![museum_war_top_no_bat_no_deed](https://github.com/pixequil/oso-game-1/assets/49569238/8deff4ca-9e40-46fa-9bcc-45f285c45837)
![museum_war_top_no_deed](https://github.com/pixequil/oso-game-1/assets/49569238/95e71763-b9b1-4158-85eb-5c242dda479e)

**Comment by funnyboy044** [comment]
epic
