### ISSUE TITLE
conversation with the now-satisfied yd and bs

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#17]
https://github.com/pixequil/oso-game-1/blob/bda13de7f02e91e6fd348a40107169783d0e5c67/game/room001-mainstreet.rpy#L142

**Comment by pixequil** [comment]
https://github.com/pixequil/oso-game-1/blob/c9953ec3e6480bd1dfa989c34c13f39644383997/game/room001-mainstreet.rpy#L143-L150

**Comment by funnyboy044** [comment]
yd "Hi Posty!"
    bs "Sup Posty, me and Yellow Diamond here are just working out the kinks of our business."
    p happy "Well, I'll leave you to it!"
    bs "So Yellow Diamond, how do we teach people with legs to fly?"
    bs "Doesn't that sound impossible?"
    yd "It's easy! You have to believe in it really hard!"
    bs "I can't help but feel I've been duped..."
