### ISSUE TITLE
imaginary deed closeup

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#170]
![image](https://github.com/pixequil/oso-game-1/assets/99515471/faa0584f-c6e9-4d85-8081-eb0414436586)
text should not be legible, other than the word deed. make sure it looks imaginary(?)

**Comment by funnyboy044** [comment]
https://drive.google.com/file/d/1UgEB0OTA0jxgyoPudFT-p7GeANg4l6fW/view?usp=sharing
![imaginary_deed](https://github.com/pixequil/oso-game-1/assets/63936011/b81961f5-eff2-4b04-9056-73023721e1c2)
credit to juul in schuul
