### ISSUE TITLE
ahiss deed conversation

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#173]
there's a lot of different logic in here based on if/when you've already spoken to Palettette@. definitely discuss in chat before tackling.

```
label .ahiss_deed:
    if item.imaginary_lighter == False:
        if saw.pal:
            p "_" # posty asks if she can at least have that battery
            ahiss "_" # ahiss is like no way
            $ battery_asked = True
        p "_" # posty is like "well i'll leave you be then" or something
        jump museum_war
    else:
        p quiet "{i}_{/i}" # posty thinks to use the imaginary lighter on the deed.
        show posty:
            xalign -0.05
        $ renpy.transition(move, layer="master") #prevents interruption of the text window
        ahiss "_" # ahiss says something as posty approaches to incinerate the deed
        hide deed
        $ renpy.transition(irisout, layer="master") #prevents interruption of the text window
        "You {b}imaginary burned{/b} the {b}imaginary deed{/b}!"
        $ deed_burned = True
        $ item.imaginary_lighter = False
        if saw.pal:
            p "_" # posty takes the battery since it belongs to palettette.
        else:
            p "_" # posty notices the battery on the ground and takes it now that she's close to it, on impulse.
        show battery center
        "You got the {b}battery{/b}!"
        $ item.battery = True
        hide battery
        if battery_asked:
            ahiss "_" # "i hope you're happy" or something
            p "_"
            ahiss "_" # ahiss finds a way to be smug about this situation in the end.
        else:
            ahiss "_" # "that's what you wanted!??" or something
            if saw.pal:
                p "_" # posty tells the truth: yes
            else:
                p "_" # posty tells the truth: no
            ahiss "_" # ahiss finds a way to be smug about this situation in the end.
        jump museum_war
```

**Comment by CONKINGTON** [comment]
### If Palettette@ isn't seen and the Imaginary Lighter isn't in the inventory
p: Dodoodoodooo I'm a little postbox appreciating the cultural masterpieces, nothing is going to distract me-
p: Ooooooh what do we have here: a little battery sad and alone.
p: Not to be judgemental, but I don't think you are meant to be here.
p: Maybe I should keep you safe for noooww-
ahiss: Ssssssssss
p: !!!
ahiss: ssSSSTAY YOUR INCURSIONS INTO MY DOMAIN OR FACE THE WRATH OF THE GREAT A. HISS CHAMPURRLAIN!!
ahiss: If you want to lay claim to any of my glittering riches, you better swear eternal fealty as the vassal to my kingdom.
p: Hahahahahaha what a funny joke hahahahahaha.
ahiss: As expected, a barbarian is unable to comprehend such basic ideas as property rights.
ahiss: Maybe THIS will change your mind!
p: ...
ahiss: I see that you are stunned by the glorious rights granted to me as Royal Regent and Progenitor to The Humble And Pure Kingdom of Osotonia-on-and-around-Fugazi-you-really-believe-this and Head of the three hundred and Nyanth Regiment!
ahiss: Your allegiance or your life: your choice...
p: Hmm what abou-
ahiss: BACK OFF YOU CHARALATAN!
p: owwwww that hurts 
ahiss: That should serve as a reminder not to go against divine authority.
ahiss: NOW FLEE!

**Comment by pixequil** [comment]
Needs to be discussed in chat to populate the conditional tree
