### ISSUE TITLE
hint for if you have the battery

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#175]

**Comment by CONKINGTON** [comment]
p: "Hmm someone seems to have lost it. What a shame."
t: "Heyyyy."
p: "What is it?"
t: "Where did you find this?"
p: "Oh, I found it in Ahiss's patch."
t: "Well that is out of character for you to take stuff without permission, my rival."
p: "WHAT?!"
t: "I may not have your smarts-"
p: "stop talking like that."
t: "but I think someone in this exhibit may have lost this recently."
t: "If I were you, I would give it to lost and found."

**Comment by pixequil** [comment]
@CONKINGTON toasty is not in the exhibit, so the hint needs to make it clearer where to return it to. maybe toasty could ask posty somehow, where the battery came from, and then guess correctly that it rolled there from someone else's possession?

**Comment by CONKINGTON** [comment]
t: What is this lying on the ground?
p: It appears to be a battery.
t: Unless this is an art piece I don't understand, this doesn't belong in the gallery!
t: In which case, my adversary, it must be returned at post haste!
p: Oh my god stop with the rivalry stuff
t: It must have rolled here into the clutches of Ahiss the Pretender, depriving its owner of its electrical power due to the injustice of private property.
t: We shall find its owner and return it, post haste!
p: _if you say "post haste" one more time, i am going to turn your slots into a Matisse rendition of a car crash_
t: But the question is, where did it roll from?
-XKZ

**Comment by pixequil** [comment]
specifically, the ingame scenario is that the player has collected the battery from ahiss's territory and exited the museum for whatever reason (likely that they were confused and needed a hint). the battery is in posty's posession, not on the ground

**Comment by CONKINGTON** [comment]
t: Heya Posty, what'cha doing?
p: Just admiring this artpiece.
t: How did a nitwit like you get so tasteful?
p: Something about the curves, the weight, the lettering that says "DO NOT EAT" embroidered so perfectly in Arial.
p: I think I can understand why people feel so strongly about art, this thing made me so passionate that I took a walk around to clear my head.
t: Where was this masterpiece discovered?
p: Well it is a long story: I basically evacuated this from some presumptous cat who was camping in the gallery.
p: Had to go on a goose chase just to get this thing, so don't think of taking it.
t: Geez, I would never.
t: If I was you, more proactive and smart,-
p: Watch it!
t: I would actually be a good Samaritan and give this thing back.
p: No way! I found this fair and square, mine!
t: You may be square, but you aren't being fair.
t: Can't wait to have moral superiority over you!

**Comment by pixequil** [comment]
Toasty is not in the museum

**Comment by CONKINGTON** [comment]
p happy: Duh duh dum, dum diddly dum-
t enthused: Hello my most perfidious postbox.
p annoyed: not again coughs so what you need?
t crossed arms: I was just wondering what you have in your hand?
p concerned: Just a battery.
t angry: That's it? I thought it would be something more valuable.
p concerned: I dunno, something intrigues me about it.
t smug: Could it be its satisfying weight, finely crafted out of the earth's treasures?
t smug: Maybe its cold metal gives tingles as though a hidden memory is unlocked from your steely heart.
p confused: Why you being so fancy with the descriptions?
t enthused: Oh! I can put my curiosities to rest-
p happy: Ahh you are finally giving me peace.
t smug: It must be the tasteful interspersion of Helvetica and Arial in "PLEASE DON'T EAT, INGEST OR SWALLOW THIS"; gives the message some much needed depth.
p concerned: you reading too much into this.
t point and laugh: How did such a nitwit like you get so tasteful?
p annoyed: ...
t: ...
t: Joking, joking.
t: Besides, why are you looking at it like that?
p concerned: I don't know. I thought a good walk could help me with that.
t smug: Wellll-
p confused: Well?
t: Give me a second, I have a call.
t turned: Looks like my cuboid companion has made a major misstep: wasting valuable energy on idle walking!
p confused: wait what?
t turned: I know the quality of art has declined rapidly in the last decade of so but I don't recall being a battery exhibit back there.
t turned: Think Toast, who would lose such an item there?
t turned: Maybe an artist, too engrossed in their crafts, dropped it behind...
t turned: Yess you are such a genius Toastmeister, I will win this challenge in no time!
p annoyed: really Toastmeister?
t turned: All we have to do is make sure our friend doesn't eavesdrop and we golden!
t turned: Hope to see you bye!
t: So whatcha going to do with the battery?

**Comment by CONKINGTON** [comment]
p happy: Duh duh dum, dum diddly dum-
t enthused: Hello my most perfidious postbox.
p annoyed: not again coughs so what you need?
t crossed arms: I was just wondering what you have in your hand?
p concerned: Just a battery.
t angry: That's it? I thought it would be something more valuable.
p concerned: I dunno, something intrigues me about it.
t smug: Could it be its satisfying weight, finely crafted out of the earth's treasures?
t smug: Maybe its cold metal gives tingles as though a hidden memory is unlocked from your steely heart.
p confused: Why you being so fancy with the descriptions?
t enthused: Oh! I can put my curiosities to rest-
p happy: Ahh you are finally giving me peace.
t smug: It must be the tasteful interspersion of Helvetica and Arial in "PLEASE DON'T EAT, INGEST OR SWALLOW THIS"; gives the message some much needed depth.
p concerned: you reading too much into this.
t point and laugh: How did such a nitwit like you get so tasteful?
p annoyed: ...
t: ...
t: Joking, joking.
t: Besides, why are you looking at it like that?
p concerned: I don't know. I thought a good walk could help me with that.
t smug: Wellll-
p confused: Well?
t normal Give me a second, I have a call.
t turned Looks like my cuboid companion has made a major misstep: wasting valuable energy on idle walking!
p confused wait what?
t I know the quality of art has declined rapidly in the last decade of so but I don't recall being a battery exhibit back there.
t Think Toast, who would lose such an item there?
t Maybe an artist, too engrossed in their crafts, dropped it behind...
t Yess you are such a genius Toastmeister, I will win this challenge in no time!
p annoyed really Toastmeister?
t All we have to do is make sure our friend doesn't eavesdrop and we golden!
t Hope to see you bye!
t normal So whatcha going to do with the battery?

**Comment by CONKINGTON** [comment]
```
elif item.battery:
show posty neutral
show toasty neutral
p happy: "Duh duh dum, dum diddly dum-"
t enthused: "Hello my most perfidious postbox."
p annoyed: "not again _coughs_ so what you need?"
t crossed arms: "I was just wondering what you have in your hand?"
p suspicious: "Just a battery."
t angry: "That's it? I thought it would be something more valuable."
p concerned: "I dunno, something intrigues me about it."
t smug: "Could it be its satisfying weight, finely crafted out of the earth's treasures?"
t "Maybe its cold metal gives tingles as though a hidden memory is unlocked from your steely heart."
p confused "Why you being so fancy with the descriptions?"
t enthused "Oh! I can put my curiosities to rest-"
p happy "Ahh you are finally giving me peace."
t smug "It must be the tasteful interspersion of Helvetica and Arial in "PLEASE DON'T EAT, INGEST OR SWALLOW THIS"; gives the message some much needed depth."
p concerned "you reading too much into this."
t point and laugh "How did such a nitwit like you get so tasteful?"
p annoyed "..."
t normal "..."
t "Joking, joking."
t "Besides, why are you looking at it like that?"
p concerned "I don't know. I thought a good walk could help me with that."
t smug "Wellll-"
p confused "Well?"
t normal "Give me a second, I have a call."
t turned "Looks like my cuboid companion has made a major misstep: wasting valuable energy on idle walking!"
p confused "...wait what?"
t "I know the quality of art has declined rapidly in the last decade of so but I don't recall being a battery exhibit back there."
t "Think Toast, who would lose such an item there?"
t "Maybe an artist, too engrossed in their crafts, dropped it behind..."
t "Yess you are such a genius Toastmeister, I will win this challenge in no time!"
p annoyed "really Toastmeister?"
t "All we have to do is make sure our friend doesn't eavesdrop and we golden!"
t "Err..hope to see you bye!"
t normal "So whatcha going to do with the battery?"
return
```
