### ISSUE TITLE
hint for after brand soda quest

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#18]
```
        t "hint for if you finished Brand Soda quest" # TODO: hint for after brand soda quest
```

https://github.com/pixequil/oso-game-1/blob/7caff8aebf32e53cb8b37b26e0544a7a551d5b08/game/toasty_hints.rpy#L16

**Comment by pixequil** [comment]
https://github.com/pixequil/oso-game-1/blob/c9953ec3e6480bd1dfa989c34c13f39644383997/game/toasty_hints.rpy#L31-L33

**Comment by PenTick** [comment]
"Maybe I should go to that Blue Exhibit. It sounds interesting!"

**Comment by funnyboy044** [comment]
show posty neutral
        show toasty neutral
        t "You deal with that Brand Soda guy yet?"
        p "Yeah. Yellow Diamond's gonna be their manager, to some degree."
        t "Oh good. Now what?"
        p "I'm not sure. I got some money out of it."
        t smug2 "Try spending it all in one place."
        p annoyed "Very funny."
        t "Ok, seriously though, try going somewhere else. You spent so much time wandering around the street with Brand Soda."
        t "Maybe you should go to that art museum. It sounds interesting!"
        t "You could the next big painting and get a fat paycheck from it!"
        t "Then you could spend your money at two places!"
        t pointandlaugh "And be twice as broke!"

**Comment by funnyboy044** [comment]
^ added pentick line, might be too on-the-nose?

**Comment by pixequil** [comment]
definitely too on the nose
