### ISSUE TITLE
blocked by retainer hint

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#19]
```
        t "hint for after you try to deliver the butterflies" # todo: blocked by retainer hint
```

**Comment by pixequil** [comment]
https://github.com/pixequil/oso-game-1/blob/c9953ec3e6480bd1dfa989c34c13f39644383997/game/toasty_hints.rpy#L35-L37

**Comment by funnyboy044** [comment]
wrote a pull request for a draft of this hint

**Comment by CONKINGTON** [comment]
t: "Well he doesn't seem happy at the moment."
t: "Perhaps if he cheers up then he will move out of the way."
t: "But what would make him happy again?"

**Comment by funnyboy044** [comment]
I think this is already closed, something's written for it in the main branch
