### ISSUE TITLE
food exhibit conversation background

### ISSUE THREAD

**Issue by funnyboy044** [pixequil/oso-game-1#190]

**Comment by funnyboy044** [comment]
Assets: https://drive.google.com/file/d/1a8D36HYxpm_C2VG4WfyVAksQyzBVlMbx/view?usp=drive_link
https://drive.google.com/file/d/1yKrwHus1RT9uXWu5KOxI32vYdTbbF5kb/view?usp=drive_link
Credit to: Plugboy

With Fire:
![Food_Exhibit_convo_bg_burger_fire](https://github.com/pixequil/oso-game-1/assets/63936011/c6d853ff-0163-4117-9959-5bc13aa4bb6e)

No fire:
![Food_Exhibit_convo_bg_burger_nofire](https://github.com/pixequil/oso-game-1/assets/63936011/3acd6495-74b3-4e6c-9978-b252ac457d18)

**Comment by funnyboy044** [comment]
I'm working on getting on the no fire one updated with actually no fire

**Comment by funnyboy044** [comment]
> I'm working on getting on the no fire one updated with actually no fire

![OSO_Game_-_Food_Exhibit_C](https://github.com/pixequil/oso-game-1/assets/63936011/369a1d76-f343-4c4a-81c1-081c03904d2f)
#

**Comment by f4nimator** [comment]
shouldn't the painting be in the war exhibit?

**Comment by pixequil** [comment]
<img width="640" alt="museum_food_dbg" src="https://github.com/pixequil/oso-game-1/assets/99515471/3e68e762-922a-475b-8687-73963f960af2">

the background should not depict any art in particular. just the sense that there's nearby art, so specific paintings can be in the background of different conversations. it should be shaped like the one in the war exhibit. i've created a placeholder based on the war exhibit's background. this one should be shaped like the placeholder (but of course illustrated to match the wallpaper etc of the food exhibit)
