### ISSUE TITLE
custom dialogue voices

### ISSUE THREAD

**Issue by funnyboy044** [pixequil/oso-game-1#201]
Just make sure to create another issue for adding custom voices for characters instead of stealing them from Undertale :P

_Originally posted by @Martysh12 in https://github.com/pixequil/oso-game-1/issues/200#issuecomment-1582715258_

**Comment by funnyboy044** [comment]
Yeh rn the default sound is snd-txt-1 from undertale and yd uses floweys voice so we gotta change that soon

probably add some new voices for other important voices

**Comment by pixequil** [comment]
duplicate
