### ISSUE TITLE
retainer is sad he got eliminated

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#21]
```
        p "_" # TODO: retainer is sad he got eliminated
```

undefined

**Comment by pixequil** [comment]
https://github.com/pixequil/oso-game-1/blob/c9953ec3e6480bd1dfa989c34c13f39644383997/game/room010-dome.rpy#L35-L41

**Comment by CONKINGTON** [comment]
p: "What's wrong?"
r: "Sigh, things hadn't been going well."
r: "Got eliminated from this show after only a couple of challenges, which was way earlier than expected."
p: "Ah shame, it happens sometimes."
r: "It was supposed to be my breakthrough moment: when I start making friends and doing more in my life."
r: "Instead I ended up here, without accolades to show for it."
r: "I don't understand why I did this in the first place, no one cared I was gone."
p: "..."
p: "May I get past you?"
r: "..."
p: "Never mind."

-credit as XKZ
