### ISSUE TITLE
Asset and devroom issues

### ISSUE THREAD

**Issue by Martysh12** [pixequil/oso-game-1#218]
A lot of assets have a white outline around them, probably because they were submitted on a white opaque background.
This issue will document all of the problems regarding assets and the devroom.

Devs - please tick each of these checkmarks as they're fixed.

 - [x] Palettette@ (white halo) (shows up twice, second time is broken)
![image](https://github.com/pixequil/oso-game-1/assets/49569238/93188735-c312-4abd-9828-46e1cff88bf8)
![image](https://github.com/pixequil/oso-game-1/assets/49569238/b2f37197-a8ad-420d-a68a-3b3138c32fe3)
 - [x] Buff (white halo) (appears twice in the devroom)
![image](https://github.com/pixequil/oso-game-1/assets/49569238/0d570712-0ce8-45e3-8766-694fb74a4728)
 - [x] Red Tile (white halo, _very slight_)
![image](https://github.com/pixequil/oso-game-1/assets/49569238/f21ce351-5e17-4e15-a4bb-af6583702543)
 - [x] Sour Gummy (white halo)
![image](https://github.com/pixequil/oso-game-1/assets/49569238/1b58e59a-1c4a-4470-9a24-4aa80b7724f4)
 - [x] Marble Bust (white halo)
![image](https://github.com/pixequil/oso-game-1/assets/49569238/aed43912-8c10-4438-96b0-a2549957d6c7)
 - [x] Blue-Colored Glasses (white halo) (why is he hiding on the right side of the screen) (appears twice in the devroom)
![image](https://github.com/pixequil/oso-game-1/assets/49569238/e4889cbd-570a-4380-852e-108aa017f439)
 - [x] Crayon Box (white halo) (faulty animation)
https://github.com/pixequil/oso-game-1/assets/49569238/da9c58b6-ee43-4d99-b3ff-ac0ac330c07f
 - [x] Dolly (shows up twice in the devroom!!!!!!)
 - [x] Blue Tile (shows up twice in the devroom)
 - [x] Capsule (shows up twice in the devroom)
 - [x] Rose-Colored Glasses (shows up twice in the devroom) (faces wrong direction)
![image](https://github.com/pixequil/oso-game-1/assets/49569238/995debb6-9704-480d-8f48-39c34df43fef)

**Comment by CONKINGTON** [comment]
![sourgummy_close](https://github.com/pixequil/oso-game-1/assets/134235512/eb96aeea-0756-4343-8ead-68a2f9e26236)
![marblebust_open](https://github.com/pixequil/oso-game-1/assets/134235512/0f962502-a7d2-450f-b604-0f562e3efa4d)
![marblebust_close](https://github.com/pixequil/oso-game-1/assets/134235512/9bb70a05-1896-4704-9470-99650842cc56)
![bcg_open](https://github.com/pixequil/oso-game-1/assets/134235512/e571bd40-fe04-4355-ade9-867433c0dac0)
![bcg_close](https://github.com/pixequil/oso-game-1/assets/134235512/cfb3f0de-5ab9-4d9c-a190-0c2b57fada92)
![crayonbox_open](https://github.com/pixequil/oso-game-1/assets/134235512/944768ba-56f2-40b0-9fce-ddd759f29b9d)
![crayonbox_close](https://github.com/pixequil/oso-game-1/assets/134235512/829c60e7-5533-4361-a00d-293ae795186a)
![sourgummy_open](https://github.com/pixequil/oso-game-1/assets/134235512/e6dd97c4-3f4d-436b-921e-068ba37ef96f)
![palettette_close](https://github.com/pixequil/oso-game-1/assets/134235512/e84258e0-0b9b-4fd8-8c34-5e2c6ac0ca10)
![palettette_open](https://github.com/pixequil/oso-game-1/assets/134235512/ffcb9926-4b07-40d7-8b6d-a3fab75afec6)
credit as XKZ

**Comment by Martysh12** [comment]
That looks good! Palettette@ still has some of that halo though

**Comment by CONKINGTON** [comment]
![redtile_close](https://github.com/pixequil/oso-game-1/assets/134235512/659fcdc1-1f4d-4121-8044-4821722d6691)
![redtile_open](https://github.com/pixequil/oso-game-1/assets/134235512/c5f747aa-5a41-49e0-ae93-a4459adfd0af)
![palettette_close](https://github.com/pixequil/oso-game-1/assets/134235512/25639de0-aee1-494e-92c9-16c9472b15e6)
![palettette_open](https://github.com/pixequil/oso-game-1/assets/134235512/5aba52a5-70c2-4735-ac40-29bfeea75885)
credit as XKZ

**Comment by funnyboy044** [comment]
all these issues come from merging issues i assume

**Comment by Martysh12** [comment]
cmon guys you gotta learn how to handle merge conflicts correctly
