### ISSUE TITLE
war main exhibit painting

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#225]
A painting depicting a certain victory in a battle. It’s monochrome

Rose-Colored Glasses claims it "clearly shows the victory of the Redoinks."

Blue-Colored Glasses claims it "clearly shows the victory of the Blouououous."

it's grayscale, so it's not clear what side is winning, or if the sides are even color-themed to begin with.

**Comment by funnyboy044** [comment]
Paintings with variations!
Credit to: SillySussy
Original: https://drive.google.com/file/d/1pbTSqJ0BdkwZDsrPpm_-xD7wE6o83dyn/view?usp=drive_link
![war_Exhibit_photo](https://github.com/pixequil/oso-game-1/assets/63936011/43390b30-f335-4e26-a4a1-cee825c0c5bf)

**Comment by funnyboy044** [comment]
I did the variations myself, so if they look bad or over-saturated, let me know and i'll fix them

**Comment by funnyboy044** [comment]
Blue: https://drive.google.com/file/d/1HF2pi4fB9nzw7-gowd95q-VFB655v_tO/view?usp=drive_link
![war_Exhibit_photo_blue2](https://github.com/pixequil/oso-game-1/assets/63936011/8cf0ccb5-c3da-4b7e-a0f0-83366dc6cc29)

Red: https://drive.google.com/file/d/1RlNpOrDBXBHirhCmAeevJ5kPFC53XGUw/view?usp=drive_link
![war_Exhibit_photo_red_3](https://github.com/pixequil/oso-game-1/assets/63936011/2f820963-d472-4c17-8c27-56608858938e)

Green: https://drive.google.com/file/d/17nfVSC6lXjcVnL52bsl59T_QDDVXLglU/view?usp=drive_link
![war_Exhibit_photo_green_3](https://github.com/pixequil/oso-game-1/assets/63936011/08d5f3be-1fe2-45f3-8611-670a2a7e5042)

Inverted: https://drive.google.com/file/d/1xf_IJY199JdYDlqpIssWY6UFdusAUC5h/view?usp=drive_link
![war_Exhibit_photo_inverted](https://github.com/pixequil/oso-game-1/assets/63936011/957797da-6353-417e-9155-688059a4fd90)
