### ISSUE TITLE
food main exhibit painting

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#226]
All of the paintings here are absolutely delicious – except for one – “Brussel Sprouts in Watercolor.” It’s in a corner, not really displayed, and no one cares if you take it, it’s yucky.

**Comment by Martysh12** [comment]
why these specific foods

**Comment by pixequil** [comment]
They are already represented in other art pieces

**Comment by Martysh12** [comment]
ah

**Comment by funnyboy044** [comment]
Art by DemiDude, implement
![Brussel_Sprouts](https://github.com/pixequil/oso-game-1/assets/63936011/25430a07-f4c0-44d5-be7e-4c939058f5ac)
