### ISSUE TITLE
secret switch scene

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#233]
```
label .eating:
    scene bg museum_food
    show eating
    show posty neutral
    if food_switch == False:
        p "_" # posty observes that the painting doesn't really belong here. these are paintings of food, not paintings of eating. she takes a look at the painting's placard, curious why it was included.
        "The title of the painting is \"{i}Crisis of the Poplar Trees{/i}\". The rest of the text is too small to read at this distance." 
        p "_" # posty remarks that that's hardly a fitting name for this painting either, and it sure as hell isnt fitting for a painting in the food exhibit.
        label .eating_decide:
        menu:
            "Read more of the placard?"

            "Yes.":
                "You try to read more of the placard, but bonk your face on it by mistake!"
                # play a sound here! like a click!!!
                # and then a scene of the corndog painting disappearing, revealing the secret passageway.
                $ food_switch = True
                p "_" # something like "well that was weird. better back off"
                jump museum_food
            "No.":
                p "_" # posty decides she is uninterested in reading more of the placard. she starts to walk away, but returns to the placard, still curious.
                jump .eating_decide
    else:
        p "_" # posty returns to actually read the placard this time.
        "The placard reads: \"{i}(something){/i}\". Weird!" # placard full text.
        p "_" # some kind of remark
        jump museum_food
```

**Comment by pixequil** [comment]
the secret passage opening will be produced after imagemaps are implemented

**Comment by CONKINGTON** [comment]
p suspicious "Huh what is that doing there? Among all the food based pieces, it doesn't look that appetizing to look at someone eating."
"The title of the painting is \"{i}Crisis of the Poplar Trees{/i}\". The rest of the text is too small to read at this distance." 
p "The only thing true about the title is that guy is clearly having a crisis about something!"
p "If I didn't know any better, I would've thought he was having some pizza psychosis..."

_Yes_
p astonished "Ooh sneaky!"
p neutral "..."
p concerned "Better step away and pretend nothing ever happened-"
p "Doodly doo do dooo just a postbox walking away from a mysterious hole in the ground in an innocent waaay!"

_No_
p "Wellll I feel like it would be stupid to mess around with forces beyond my understanding."
p "There are a lot of people in here who are... well connected to say the least."
p "Better not interfere with affairs I don't know of!"
p neutral "..."
p concerned "But on the other hand, this painting really draws me in."
p "I know I shouldn't poke around, buuuutt then I would have to deal with not knowing why this piece exists."
p "Who is this guy? Why does he have a slice? Where is he being kept? Who painted this? Why is he angry? Did the painter survive and if so, where can I find them? Why why why why-"
p zany "Damn just thinking about this drives me NUTS!"
p suspicious "Wouldn't hurt just to think about it some more..."

**Comment by pixequil** [comment]
added some of this. the rest needs to be replaced to better match the context of the scene
