### ISSUE TITLE
hint for if you opened the janitors closet but didnt go in

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#234]

**Comment by CONKINGTON** [comment]
p zany "Woaaaah I think I am seeing stars!"
p concerned "Owww my head hurts!"
toasty smug2 "What is up..."
toasty neutral "Dude are you alright?"
p "I bonked my head on the corndog painting."
p sad "It hurts."
toasty "Damn..."
toasty pointandlaugh "Looks like I have an advantage against my hated blue rival!"
toasty smug "Looks like I need to do my planning in secret!"
p angry "..."
toasty turned "What up Toastmeister!"
p "you still sticking with Toastmeister?"
toasty "The blue buffoon doesn't understand the significance of this painting!"
toasty "and no we aren't just talking about its culinary delights!"
p "ha ha ha"
toasty "If my detective skills are correct (and I have no reason to doubt my glorious abilities), this is a hidden passageway!"
toasty "But Meister! Surely no one would conceal such a secret in such a seen scene!"
toasty "Ahh elementary my pop up Watson! Maybe they have a certain hidden panel..."
toasty "Say in an inconspicuous place that any intruder wouldn't care to look..."
toasty "Like a plaque on a novelty painting!"
toasty "Press this down and hey presto: you got a pathway to your nook!"
toasty "Genius! You deserve a raise for such logic."
toasty "Phew I don't deserve such praise, now lets keep it away from prying ears!"
toasty neutral "Soooooo how is the weather my courier companion?"
