### ISSUE TITLE
Squirt Bottle confronts you about how you got in his closet

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#236]

**Comment by CONKINGTON** [comment]
p: ...heya.
sq: susndjsdjsifjsdk how did'ya get here?
p: umm I don't know... errrrm nice chairs?
sq: You don't get to complement my chairs unless I invite you in. And I don't recall sending invitations.
p: Errrrrrr.
sq: _sigh_, fine you can stay here.
sq: Not because I am happy to do so, but because you would be too much of a pain to evict.
sq: Don't tell anyone about this.
p: Not a single word will come out about this sir.
sq: ...
sq: Don't be so formal, just call me Squeezy.
sq: While you here, help yourself to a snack.

**Comment by pixequil** [comment]
I like the finisher, but I can't remember if Squirt Bottle has an issue with snacks being taken. Can someone double check about that

**Comment by CONKINGTON** [comment]
> I like the finisher, but I can't remember if Squirt Bottle has an issue with snacks being taken. Can someone double check about that

Checked the script, Squeeze Bottle doesn't seem to care about his snacks, just doesn't like people appearing in his secret room

**Comment by pixequil** [comment]
Really! I'm surprised, I feel like there was some kind of conversation initiated if you interact with the machine

**Comment by f4nimator** [comment]
i edited it a bit because i think it would be better for him to care so the vending machine scene makes sense.
```
    p "...heya."
    $ renpy.transition(hpunch, layer="master")
    sb "AHGDHSXJS- How d'ya get here!?"
    p "Umm I don't know... Errrrm nice chairs?"
    sb "You don't get to complement my chairs unless I invite you in. And I don't recall sending invitations."
    p "Errrrrrr.."
    sb "{i}sighh{/i}  Fine! you can stay here."
    sb "Not because I am happy to do so, but because you would be too much of a pain to evict."
    sb "Don't tell anyone about this."
    p happy "Not a single word will come out about this sir!"
    sb quiet "..."
    sb -quiet "Don't be so formal, just call me Squeezy."
    sb "Do whatever, I guess."
```

**Comment by f4nimator** [comment]
oh also you can make it so sb is facing the other way at first before noticing posty with this code:
```
...
init:
    transform flip: 
        xzoom -1.0

...
```
^ doesnt matter where that is as long as its above the code below
```
...
    show sb:
        flip
        right
    $ saw.janitors = True
    p suspicious quiet "{i}Whats this place?{/i}"
    p neutral "...heya."
    hide sb
    show sb # resets sb so hes facing the correct way
...
```

**Comment by CONKINGTON** [comment]
```
   init:
    transform flip: 
        xzoom -1.0
    show sb:
        flip
        right
    $ saw.janitors = True
    p suspicious quiet "{i}Whats this place?{/i}"
    p neutral "...heya."
    hide sb
    show sb # resets sb so hes facing the correct way
    $ renpy.transition(hpunch, layer="master")
    sb "AHGDHSXJS- How d'ya get here!?"
    p "Umm I don't know... Errrrm nice chairs?"
    sb "You don't get to complement my chairs unless I invite you in. And I don't recall sending invitations."
    p "Errrrrrr.."
    sb "{i}sighh{/i}  Fine! you can stay here."
    sb "Not because I am happy to do so, but because you would be too much of a pain to evict."
    sb "Don't tell anyone about this."
    p happy "Not a single word will come out about this sir!"
    sb quiet "..."
    sb -quiet "Don't be so formal, just call me Squeezy."
    sb "Do whatever, I guess."
```
