### ISSUE TITLE
dome conversation bg

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#24]
```
# TODO: dome conversation bg
```

https://github.com/pixequil/oso-game-1/blob/f6faaf1c0fee9b387c1b6e130fc5fbaaeba9e9ed/game/room010-dome.rpy#L6

**Comment by pixequil** [comment]
https://github.com/pixequil/oso-game-1/blob/c9953ec3e6480bd1dfa989c34c13f39644383997/game/room010-dome.rpy#L6

**Comment by funnyboy044** [comment]
Asset: https://drive.google.com/file/d/1MpHvemICf1PX3WLYDgpmBLXaLEl26mDA/view?usp=sharing

Credit: Rand0m00

implement this ^
