### ISSUE TITLE
hint for if you got the chips

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#242]

**Comment by PlugBoyOfficial** [comment]
p "You want some Generi-Chips?"
toasty "Lol, no!"
toasty "Why'd you even get those anyway, I thought you hated them!"
p "Argh! That's exactly why I'm trying to get rid of them!"
toasty "Hmph. Well, where'd you get those chips anyway?"
p "...uh...the...museum...?"
toasty "...Have you asked somebody in the museum if they want them?"
p "...no, I don't think so."
toasty "Hah! You really are stupid, aren't you?"
