### ISSUE TITLE
base notepad interactions

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#244]
```
label .notepad1:
    show posty neutral
    $ saw.notepad = True
    notepad "_" # notepad explains their whole deal. A starving artist (emphasis on “starving”)/doodler who has had no luck in convincing any curators to buy their art for any price. They’re extremely upset and hungry, and will trade their art for food at this point.
    if item.chips:
        jump .notepad_chips
    else:
        p "_" # posty apologizes, not having any food for them.
        notepad "_" # notepad tells her to let them know if they find any for them
        jump museum_food

label .notepad2:
    show posty neutral
    notepad "_" # notepad asks posty if she has any food for them now.
    if item.chips:
        jump .notepad_chips
    else:
        p "_" # posty apologizes, as she still doesn't.
        notepad "_" # notepad reminds her to let them know if they find any for them
        jump museum_food
```

**Comment by funnyboy044** [comment]
There's still some parts of #244 that need to be written out
- the else statement of .notepad1
- all of .notepad2

**Comment by funnyboy044** [comment]
label .notepad1: #244
    show posty concerned
    $ saw.notepad = True
    p "Oh my, are you alright?"
    notepad "Can't you tell?! I am rock bottom here."
    notepad "I have turned my whole damn life upside down for the chance of exhibitions and I can't even find a bite to eat!!"
    notepad "Many times I pleaded and begged the curators to buy my life's work, many times they rejected me..."
    p sad "Damn that sucks."
    notepad "Not even half of it: I even reduced my prices all the way down to $2 for everything I ever made."
    notepad "You know what they said? No!"
    notepad "I am at my wits end: starving in the middle of the food exhibit."
    notepad "I should've stayed back home, then I wouldn't have ended up here."
    notepad "Time after time I put so much heart into this, only to be thrown out like a stray cup."
    notepad "I don't know why I bother."
    if item.chips:
        jump .notepad_chips
    else:
        p "_" # posty apologizes, not having any food for them.
        notepad "_" # notepad tells her to let them know if they find any for them
        jump museum_food



label .notepad2: #244
    show posty neutral
    notepad "_" # notepad asks posty if she has any food for them now.
    if item.chips:
        jump .notepad_chips
    else:
        p "_" # posty apologizes, as she still doesn't.
        notepad "_" # notepad reminds her to let them know if they find any for them
        jump museum_food

**Comment by funnyboy044** [comment]
label .notepad1: #244
    show posty concerned
    $ saw.notepad = True
    p "Oh my, are you alright?"
    notepad "Can't you tell?! I am rock bottom here."
    notepad "I have turned my whole damn life upside down for the chance of exhibitions and I can't even find a bite to eat!!"
    notepad "Many times I pleaded and begged the curators to buy my life's work, many times they rejected me..."
    p sad "Damn that sucks."
    notepad "Not even half of it: I even reduced my prices all the way down to $2 for everything I ever made."
    notepad "You know what they said? No!"
    notepad "I am at my wits end: starving in the middle of the food exhibit."
    notepad "I should've stayed back home, then I wouldn't have ended up here."
    notepad "Time after time I put so much heart into this, only to be thrown out like a stray cup."
    notepad "I don't know why I bother."
    if item.chips:
        jump .notepad_chips
    else:
        p "_" # posty apologizes, not having any food for them.
        notepad "_" # notepad tells her to let them know if they find any for them
        jump museum_food

**Comment by CONKINGTON** [comment]
notepad "Hey dude, you have any food?"
p concerned "Sorry, I don't have a crumb on me."
notepad "If you find some, please give it to me: I can hear my rumbles from here!"
p "Will do will do."
