### ISSUE TITLE
describe napkin painting

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#245]
A shoddy painting (in a dirty napkin, not even in a canvas!) made by someone who was pretty much just starving. Maybe someone with different tastes could appreciate this more than you.

make sure to include that:

you (posty) consider this 'painting' to have no artistic merit, as it completely fails to capture your interest even a little bit, and could never possibly serve as any sort of inspiration for you. you are not drawn to it in any way. it almost seems like a piece of trash to you.

**Comment by pixequil** [comment]
it's not even painted.

**Comment by CONKINGTON** [comment]
They say art is in the eye of the beholder: you behold this piece as a bunch of scribbles on a slightly crumpled napkin.
