### ISSUE TITLE
posty has "a lot of" money

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#250]
```
    elif money == 2: #250
        show cash_bundle_2
        p "i have a lot of money" #  posty has "a lot of" money
        dolly "_" # dolly thinks this is sufficient for the loot box, although she pretends briefly that it's not, to mess with Posty. 
        "{b}{color=#e3d3ab}Dolly{/color}{/b} took all your {b}money{/b}!"
        if item.red_cash:
            "... except the worthless {b}{color=#ff0000}red cash{/color}{/b}."
        dolly "_" # "much appreciated!"
        p "_" # "... so, the loot box?"
        dolly "_" # "right!"
        show lootbox #266
        "..." #268 insert gratuitous lootbox opening animation, reminiscent of predatory gacha games
        hide lootbox
        show scrapmetal #269
        $ item.scrapmetal = True
        $ quest.moneys = True
        "You got some {b}scrap metal{/b} from the loot box!" #270
        p "_" # this disappoints and upsets posty, but Dolly will offer no refunds.
        jump mainstreet
```

**Comment by funnyboy044** [comment]
elif money == 2: #250
        show cash_bundle_2 at truecenter
        p happy "I've got plenty of money. Here you go." #  posty has "a lot of" money
        dolly "Hmmm, sorry. You're still short."
        p astonished "What?!?"
        dolly "Haha, I'm just screwing with you. Of course you have enough." # dolly thinks this is sufficient for the loot box, although she pretends briefly that it's not, to mess with Posty. 
        show posty angry
        hide cash_bundle_2
        "{b}{color=#e3d3ab}Dolly{/color}{/b} took all your {b}money{/b}!"
        if item.red_cash:
            "... except the worthless {b}{color=#ff0000}red cash{/color}{/b}."
        dolly "Your patronage is appreciated." # "much appreciated!"
        p suspicious "So, the loot box!" # "... so, the loot box?"
        dolly "Oh yes, of course!"
        dolly "Let's see what you've won!" # "right!"
        show lootbox at truecenter #266
        "..." #268 insert gratuitous lootbox opening animation, reminiscent of predatory gacha games
        hide lootbox
        show scrapmetal at truecenter #269
        $ item.scrapmetal = True
        $ quest.moneys = True
        "You got some {b}scrap metal{/b} from the loot box!" #270
        p annoyed "Oh. Wow."
        dolly "Thank you! Come again! No refunds!" # this disappoints and upsets posty, but Dolly will offer no refunds.
        jump mainstreet
