### ISSUE TITLE
3 paintings combined

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#253]

**Comment by funnyboy044** [comment]
All the main art pieces have to be done first

- [ ] Food Exhibit Art Piece

- [ ] War Exhibit Art Piece

- [ ] Blue Exhibit Art Piece

**Comment by pixequil** [comment]
- [ ] #226 
- [ ] #225 
- [ ] #122

**Comment by funnyboy044** [comment]
Asset: https://drive.google.com/file/d/1d1i8p9M_-YsyCU9EYk3BjyafSB2qzwrU/view?usp=sharing
![All_Art_Pieces_Combined_Piece](https://github.com/pixequil/oso-game-1/assets/63936011/8de5d0ee-755e-47a6-8d35-90c97bbdd5e7)
credit to ARTTGOG
