### ISSUE TITLE
talking to security cameron after receiving the note of reprimand

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#254]

**Comment by CONKINGTON** [comment]
sc: Well well well, if it is the three piece vandal herself.
sc: You know, that notice of reprimand is the greatest punishment I can give to anyone in this place, so you watch your step.
sc: Kidding, kidding. Not that much of a deterrent to be honest, what with the little kiddies turning it into a game.
sc: Back at my last job, I would've punted you and that salty saboteur out the door faster than you can say "paintbrush"!
sc: Enough rambling, really need to keep my eye to ensure history doesn't get anymore burnt...
sc: or covered in soup.

**Comment by pixequil** [comment]
Good, needs directing

**Comment by CONKINGTON** [comment]
sc: Well well well, if it is the three piece vandal herself.
sc: You know, that notice of reprimand is the greatest punishment I can give to anyone in this place, so you watch your step.
p scared: ...
sc: Kidding, kidding. Not that much of a deterrent to be honest, what with the little kiddies turning it into a game.
sc: Back at my last job, I would've punted you and that salty saboteur out the door faster than you can say "paintbrush"!
sc: Enough rambling, really need to keep my eye to ensure history doesn't get anymore burnt...
sc: or covered in soup.

**Comment by funnyboy044** [comment]
show posty neutral
        #254 talking to security cameron after receiving the note of reprimand
        cameron "Well well well, if it isn't the three piece vandal herself."
        cameron "You know, that notice of reprimand is the greatest punishment I can give to anyone in this place, so you watch your step."
        p astonished quiet "..."
        cameron "Kidding, kidding. Not that much of a deterrent to be honest, what with the little kiddies turning it into a game."
        cameron "Back at my last job, I would've punted you and that salty saboteur out the door faster than you can say \"paintbrush\"!"
        cameron "Enough rambling, really need to keep my eye open to ensure history doesn't get anymore messed with..."
        cameron "or burnt..."
        cameron "or covered in soup."
