### ISSUE TITLE
notice of reprimand illustration

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#255]

**Comment by funnyboy044** [comment]
Asset: https://drive.google.com/file/d/1tQ_NhJIjTHYr2ctvgYAeJtAyShws3wbw/view?usp=drive_link
![notice_of_Repremand](https://github.com/pixequil/oso-game-1/assets/63936011/11fba056-ff35-4e18-b413-e0cdda44e877)
Credit: YvanBFB Animations
