### ISSUE TITLE
loot box illustration

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#266]

**Comment by funnyboy044** [comment]
https://drive.google.com/file/d/1CWBQxHfRyY40_V8HWwudrr9F6V77-iOY/view?usp=drive_link
![cash_bundle_2](https://github.com/pixequil/oso-game-1/assets/63936011/a6321f09-435a-4eef-b188-9822bc091f00)
credit to partyslime

**Comment by funnyboy044** [comment]
Asset: https://drive.google.com/file/d/1LXEH2hHVzViUr5DAqB7fRrlpS8IfQCbd/view?usp=drive_link
![dolly_lootbox](https://github.com/pixequil/oso-game-1/assets/63936011/c94139ed-4c5a-4d73-bf62-d8976a0868dc)
Credit to: F4n¡matør  (or just Fanimator if you cant use the symbols)
