### ISSUE TITLE
scrap metal illustration

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#269]

**Comment by funnyboy044** [comment]
Asset: https://drive.google.com/file/d/1cKoSUr3omx7F3sPeMJvWublbC2mFfmI8/view?usp=sharing
![scrap_metal_transparent (1)](https://github.com/pixequil/oso-game-1/assets/63936011/bdfd1ee4-d502-40a3-9af0-8fc499cb7277)
Credit to: CrispBacon
