### ISSUE TITLE
Security Cameron minisprite

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#27]
```
    show cameron # TODO: Security Cameron talksprite
```

https://github.com/pixequil/oso-game-1/blob/c2468fc001bf8e61eca61ad72bab613699563c5a/game/room003-museum_entrance.rpy#L13

**Comment by pixequil** [comment]
https://github.com/pixequil/oso-game-1/blob/c9953ec3e6480bd1dfa989c34c13f39644383997/game/room003-museum_entrance.rpy#L29

**Comment by pixequil** [comment]
![](https://cdn.discordapp.com/attachments/534177911696261120/1109531900462243920/image.png)

**Comment by pixequil** [comment]
![Security_Cameron](https://github.com/pixequil/oso-game-1/assets/99515471/e459e1c3-bb4d-46a7-a69f-5b44ca2e2b91)

**Comment by pixequil** [comment]
huh. you know? this overworld sprite might be better suited as a talksprite. renaming issue.

**Comment by funnyboy044** [comment]
Asset: https://drive.google.com/file/d/1UgME8Jaqkm3ttb8xl4j-JVEm3OVvZGF3/view?usp=sharing

Credits: multi

**Comment by funnyboy044** [comment]
implement this ^

**Comment by pixequil** [comment]
did it (in the outlining branch)
