### ISSUE TITLE
Binoculars talksprites

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#274]

**Comment by funnyboy044** [comment]
Credit to Budd3rScotch
https://drive.google.com/drive/folders/1XTDjZMv6ljBI728Ml7WS9YDtT4houwbq?usp=drive_link
A lot of sprites, we may not have to use all of them

![binoculars_exp6_close](https://github.com/pixequil/oso-game-1/assets/63936011/938b4418-eb88-4d94-a119-c0df3610bb1f)
![binoculars_exp6_open](https://github.com/pixequil/oso-game-1/assets/63936011/ff53b068-c3e1-4e60-87fc-b3c049704b01)
![binoculars_exp5_close](https://github.com/pixequil/oso-game-1/assets/63936011/14aacbf7-f873-4d96-b08a-63075fc810aa)
![binoculars_exp5_open](https://github.com/pixequil/oso-game-1/assets/63936011/ca720082-8652-4034-84ed-662ddc44736c)
![binoculars_exp4_close](https://github.com/pixequil/oso-game-1/assets/63936011/2b70529e-d94c-45f7-8d4c-6273b130151b)
![binoculars_exp4_open](https://github.com/pixequil/oso-game-1/assets/63936011/7b10b57e-d736-4cef-8e66-559c7d7f5cf4)
![binoculars_exp3_close](https://github.com/pixequil/oso-game-1/assets/63936011/d9b77c32-b7b8-475d-9930-6abe7e98ed92)
![binoculars_exp3_open](https://github.com/pixequil/oso-game-1/assets/63936011/cdc61ae9-75e3-4e5e-85fc-4db17f8484b6)
![binoculars_exp2_close](https://github.com/pixequil/oso-game-1/assets/63936011/c9ea6173-d336-4261-a9e8-51d1689688b8)
![binoculars_exp2_open](https://github.com/pixequil/oso-game-1/assets/63936011/b444ab40-0a0f-43ec-9624-f556e0c8bbab)
![binoculars_exp1_close](https://github.com/pixequil/oso-game-1/assets/63936011/31dd8319-5e1b-476f-bc57-fbc9a27713d2)
![binoculars_exp1_open](https://github.com/pixequil/oso-game-1/assets/63936011/6a921db7-4fcd-4581-a278-0f3c69c5cbd7)

**Comment by pixequil** [comment]
Let's strive for greatness! All of them will be used :)
