### ISSUE TITLE
base tooly interactions

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#276]
```
label .tooly1:
    show posty neutral
    p "_" # introduce tooly. A toolbox, and a rough but jovial metalworker. She is always equipped with sorts of metalworking equipment and runs a small workshop in front of the closed store on the east side of the street.
    tooly "_" # she offers to craft stuff if you ever bring her some raw materials
    if item.scrapmetal:
        jump .tooly_scrap
    else:
        p "_" # posty says goodbye

label .tooly2:
    show posty neutral
    tooly "_" # tooly reminds posty that she can craft stuff if you ever bring her some raw materials
    if item.scrapmetal:
        jump .tooly_scrap
    else:
        p "_" #posty says goodbye
```

**Comment by funnyboy044** [comment]
**label .tooly1:**
show posty happy
    tooly "Howdy stranger! The name's Tooly! Welcome to my shop!"
    p happy "Hello! I never noticed this place before!" 
    tooly "I just opened it!" 
    p happy "Neat! What do you do here!"
    tooly "Oh, I store nukes!"
    show posty concerned
    tooly "We have weapons of mass destruction of all shapes and sizes."
    tooly "We actually have a few deactiviated ones. Don't touch them, they're sensitive."
    p concerned "Uhhhhhhh..." 
    tooly "Hahaha! I'm just messing with you!" 
    tooly "This is a metalworking shop. Been working professionally for the past twenty years!" 
    tooly "I've got plenty of experience so if you wanted anything special crafted, I can do it pretty easily!"
    p happy "Cool!"
    tooly "It would cost you though."
    tooly "Raw materials aren't cheap."
    p concerned "Oh, I'm kinda broke."
    p concerned "Would it be cheaper if I just loaned you the raw materials myself?" 
    tooly "Hmmmm..."
    tooly "You seem like a nice enough guy, so tell you what!"
    tooly "Just for being my first customer of the day, if you personally bring me the raw materials to craft anything, I'll do your first job completely free!"
    p happy "Awesome!"
    $ saw.tooly = True
    if item.scrapmetal:
        jump .tooly_scrap
    else:
        p "See you later, Tooly!" # posty says goodbye
        tooly "Later, gator."
        jump mainstreet

**label .tooly2: #276**
    show posty neutral
    show posty happy
    p "Hey Tooly!"
    tooly "Hey customer!"
    p "Can you remind me of our deal again?"
    tooly "Wasn't expecting you to have dementia, but..."
    tooly "Just for being my first customer of the day, if you personally bring me the raw materials to craft anything, I'll do your first job completely free!"
    p "Awesome!"
    if item.scrapmetal:
        jump .tooly_scrap
    else:
        p "See you later, Tooly!"
        tooly "Later, gator."
        jump mainstreet
