### ISSUE TITLE
tooly crafting interaction

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#277]
```
label .tooly_scrap:
    p "_" # "oh, something like this?"
    show scrapmetal
    "You handed over the {b}scrap metal{/b}!"
    $ item.scrapmetal = False
    hide scrapmetal
    tooly "_" # tooly immediately knows what to do with this
    $ trophy_crafted = True
    show scraptrophy
    "Tooly crafted a {b}scrap trophy{/b}!"
    $ item.scrap_trophy = True
    hide scraptrophy
    if item.spraypaint:
        call trophy
        tooly "_" # tooly comments on your use of the spray paint
        jump mainstreet
    else:
        p "_" # some kind of thank-you
        jump mainstreet
```

**Comment by funnyboy044** [comment]
label .tooly_scrap: #
    show posty happy
    show scrapmetal at truecenter
    p "Will this work as raw materials?"
    tooly "Looks great! Hand it over!"
    "You handed over the {b}scrap metal{/b}!"
    $ item.scrapmetal = False
    hide scrapmetal
 p "Can you craft this into a trophy please?"
    tooly "Sounds good! I know exactly what to how it! Can I get the name for this project?"
    p "Posty."
    tooly "Alright, Posty! Give me one minute!"
    $ trophy_crafted = True
    show scraptrophy
    "Tooly crafted a {b}scrap trophy{/b}!"
    $ item.scrap_trophy = True
    hide scraptrophy
    p "Wow, it looks like a real trophy!"
    tooly "Yeah, the craftsmanship is good...but I don't know."
    tooly "It's missing something. It needs the perfect finishing touch."

    if item.spraypaint:
        call trophy
    tooly "Now that's a gold trophy!"
        tooly "You might be able to trick somebody into thinking this is real gold!"
        jump mainstreet

else:
p "This looks perfect! Thank you so much!"
tooly "Hehe! Any time Posty."
tooly "Catch you later!"
jump mainstreet
