### ISSUE TITLE
talking to automatone.

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#286]
A businessman taking a break in the park, because all the construction on main street has made trying to get to work into a futile act. He mentions that things were already complicated with Blob not there to help the company, and this is another problem on top.

**Comment by CONKINGTON** [comment]
label .auto:
    scene bg park
    show posty neutral
    show auto bothered
    auto "Oh god oh god oh god how can I explain this?!" 
    p "Oh what seems to be the issue sir?"
    auto "My business is trying to make a contract and I am unable to make it-"
    p concerned "On time?"
    auto "At all!"
    auto "Apparently there are a lot of orange cones everywhere in main street, major construction works."
    auto "I don't know why NOW of all times they strike at once, but now I am in a major predicament."
    p concerned "Woah you must be some really important person if you stressing like that!"
    auto "I wish, I just own a small legal services firm in the cheapest part of the city: that contract is all I'd got!"
    auto "'Autonome you should really polish your legal chops by defending the weakest in society!' they said"
    auto "'It will show strong moral character, everyone will hire you with huge bonuses and call you a hero!!'"
    auto "Well I walked the walk, and it sure hurts!"
    auto "Back at law school they called me Mr 100, they'd vote me as Most Likely To Be President!"
    auto "President!"
    auto "Instead I have to act all like Mr Community Service for stir fry and pennies and working with certain shifty purple wannabe   drink mascots who refuse to pay their retainer fee just to cover the salaries!!!"
    p "Oh damn you have a lot on your plate."
    auto "And to top it all off, I have only three other guys to help me: Mop currently sick with the flu, Playing Cards is desperately keeping the client happy and Mr Blob decided one day to join some random gameshow and disappeared ever since!"
    p astonished "Wait... you know Blob?"
    auto "Yeah, he was supposed to do all the background stuff: sorting through paperwork, answering calls and all that."
    auto "He was really top notch at that, although he had... certain quirks.
    p suspicious "quirks?"
    auto "He wasn't much of a social butterfly."
    auto "Every day he would clock in on the dot, clock out on the dot."
    auto "Didn't show much interest in me, Mop or Cards beyond the check and hours; lost my coffee money trying to get him interested in mahjong."
    auto "Couldn't tell an East from a Spring!"
    auto "Anyway sorry for that tangent, now where was I?"
    p concerned "Blob from OSO left your business?"
    auto "Ah yeah, one day he left me a letter telling me that he was going to be rich soon."
    auto "Since then, business has been hectic to say the least."
    auto "I wish he would come back..."
    auto "Oh it is Playing Cards! Hopefully she can pull this through.
    auto "...hello"
    auto "...mhm"
    auto "..."
    auto sad "...oh."
    auto "I see."
    auto "............"
    auto "Thanks, see you soon."
    p concerned "Did you keep it?"
    auto  "..."
    auto "We lost the deal."
    jump park
