### ISSUE TITLE
posty, finished with her work for the day, finally decides to take a nap on the bench!

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#290]

**Comment by CONKINGTON** [comment]
It had been a long and busy day.

What was supposed to be a simple delivery of some butterflies became a hectic blur of tasks, people and talking as she met with a wide variety of people throughout the city.

Some people lived lives that were beyond her comprehension; artists, connoisseurs, wannabe marketers, lords even!

As the weight of sleep gradually settled, she felt a sense of satisfaction.

Another job well done!

**Comment by pixequil** [comment]
this is good and can be included but we should also have some posty dialogue, even if it is an internal monologue

**Comment by CONKINGTON** [comment]
It had been a long and busy day.
p: It sure was!
What was supposed to be a simple delivery of some butterflies became a hectic blur of tasks, people and talking as she met with a wide variety of people throughout the city.

Some people lived lives that were beyond her comprehension; artists, connoisseurs, wannabe marketers, lords even!
p: I didn't even know they were still around!

Well, "lords".

As the weight of sleep gradually settled, she felt a sense of satisfaction.

Another job well done!
p: zzzzzz
-XKZ

**Comment by CONKINGTON** [comment]
"It had been a long and busy day."
p "It sure was!"
"What was supposed to be a simple delivery of some butterflies became a hectic blur of tasks, people and talking as she met with a wide variety of people throughout the city."
"Some people lived lives that were beyond her comprehension; artists, connoisseurs, wannabe marketers, lords even!"
p astonished "I didn't even know they were still around!"
"Well, 'lords'."
"As the weight of sleep gradually settled, she felt a sense of satisfaction."
"Another job well done!"
p "zzzzzz"
