### ISSUE TITLE
hint for if you made retainer leave but didnt talk to crayon box

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#292]

**Comment by CONKINGTON** [comment]
p: Oof I glad I made Retainer happy again, I can't wait to take a nap.
t: Ohohoho what do we have here : thinking of turning truant for the treacherous mistress known as sleep?
p: Stop speaking like a Victorian; you don't appear to have anything better to do.
t: I concede that I am not the shiniest appliance in this messy kitchen we call life, but I don't recall you having a keen interest in lepidopterology-
p: And I don't recall asking you what you think!
t: Ahh, the postbox doth protests too much methinks! The sore words of a loser who trips just before the finish line!

**Comment by pixequil** [comment]
Love it. Needs directing

**Comment by CONKINGTON** [comment]
p happy: Oof I glad I made Retainer happy again, I can't wait to take a nap.
t point and laugh : Ohohoho what do we have here : thinking of turning truant for the treacherous mistress known as sleep?
p annoyed: Stop speaking like a Victorian; you don't appear to have anything better to do.
t smug: I concede that I am not the shiniest appliance in this messy kitchen we call life, but I don't recall you having a keen interest in lepidopterology.
p annoyed: Lepidoptrolowhat? Is that even a word or are you trying to get one up on me?
t crossed arms: Hmph: if you were even a hundredth as diligent and scholarly as me, you would've realized that lepidopterists would kill to even touch the package you hold right now.
t smug : Who knows, if you are careless enough, maybe even little old me may take a swipe of it!

**Comment by CONKINGTON** [comment]
```
elif quest.retainer:
show posty neutral
show toasty neutral
p happy "Oof I glad I made Retainer happy again, I can't wait to take a nap."
t point and laugh "Ohohoho what do we have here : thinking of turning truant for the treacherous mistress known as sleep?"
p annoyed "Stop speaking like a Victorian; you don't appear to have anything better to do."
t smug "I concede that I am not the shiniest appliance in this messy kitchen we call life, but I don't recall you having a keen interest in lepidopterology."
p suspicious "Lepidoptrolowhat? Is that even a word or are you trying to get one up on me?"
t crossed arms "Hmph: if you were even a hundredth as diligent and scholarly as me, you would've realized that lepidopterists would kill to even touch the package you hold right now."
t smug  "Who knows, if you are careless enough, maybe even little old me may take a swipe of it!"
return
```
