### ISSUE TITLE
ticket booth conversations

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#293]
```
label .tb:
    scene bg mainstreet
    if party_bs:
        show posty neutral
        show bs follow behind posty
        show tb shy
        p "_" # ticket booth is too shy to speak to such a large group
        jump mainstreet
    if saw.tb:
        show posty neutral
        show tb neutral
        p "_" # talking to ticket booth a second time
        jump mainstreet
    else:
        show posty neutral
        show tb shy
        p "_" # talking to ticket booth for the first time
        $ saw.tb = True
        jump mainstreet
```

**Comment by funnyboy044** [comment]
if saw.tb:
        show posty neutral
        show tb neutral
        p "Hi again!" # talking to ticket booth a second time
        tb "Oh, hello!"
        tb "Heh heh..."
        p "Isn't working in front of a theater a bit of a strange career choice for you?"
        tb "I don't know...it pays well."
        tb "Though what I really want to do is work on Broadway."
        p happy "Good luck with that!"
        jump mainstreet
    else:
        show posty neutral
        show tb shy
        p "Hi!" # talking to ticket booth for the first time
        tb "H-hi!"
        tb "What movie are y-you interested in seeing?"
        p "Oh, no movies for now. I'm delivering something important for work."
        tb "Ok! Come again!"
        $ saw.tb = True
        jump mainstreet
