### ISSUE TITLE
jukebox's quick greeting

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#295]

**Comment by BumpBob** [comment]
Jukebox: Hello, Posty!
Posty: Hi, Jukebox hows it going.
Jukebox: I'm doing fine, but I've been thinking of what could be my favorite song.
Posty: Let's listen to them all and pick which one.
Jukebox: Good idea.

**Comment by pixequil** [comment]
@funnyboy044 leaving this one to you since you're the one who's been adding stuff to the music room
