### ISSUE TITLE
jukebox first conversation

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#296]

**Comment by CONKINGTON** [comment]
Jukebox (jb): Heya I am Jukebox  (Juke for short).
jb: I am the go-to for any and all music formats, from vinyls to digital!
jb: If you have a record you dream playing but you don't have the equipment, just give it to me and hear it in crisp detail!
jb: Hell I have some tracks of my own that you would jive to!
-XKZ

**Comment by pixequil** [comment]
@funnyboy044

**Comment by funnyboy044** [comment]
Combined what was written here and was written in by BumpBob in #295 to make an extended first greeting from jukebox
        jb "Sup, I'm Jukebox (Juke for short)."
        p "Hello, Jukebox! I'm Posty!"
        jb "Hey Posty, how's it going?"
        p "I'm doing well, but I've been contemplating what song could be my favorite."
        jb "Well lucky for you, I'm the go-to for any and all music, from vinyls to digital!"
        jb "If you have a record you dream playing but you don't have the equipment, just give it to me and hear it in crisp detail!"
        jb "I even have some tracks of my own that you could listen to!"
        jb "Let's hear them all and you can pick a favorite later."
        p "Great idea."
