### ISSUE TITLE
jukebox repeat conversation

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#297]

**Comment by funnyboy044** [comment]
show posty neutral
    p "What is it you do again?"
    jb "I can play any music you give me!"
    jb "Whether its the music in this game or some original music of my own, I can play it and swap out the music in this store!"
    show posty confused
    jb "I even have some remixed OSO tracks!"
    p confused "The music in this what?"
    jb "The music in this store."
    p neutral"Oh OK. Sorry for mishearing you."
    jb "That's OK, I get that all the time."
