### ISSUE TITLE
rewrite easel narration

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#30]
```
    "There are three {b}easels{/b} here." # TODO: rewrite easel narration
```

https://github.com/pixequil/oso-game-1/blob/45155f09ac24e3209ca26f0892bb42b00a2e0331/game/room003-museum_entrance.rpy#L39

**Comment by pixequil** [comment]
https://github.com/pixequil/oso-game-1/blob/c9953ec3e6480bd1dfa989c34c13f39644383997/game/room003-museum_entrance.rpy#L35-L44

**Comment by CONKINGTON** [comment]
You can see three easels in front of you.

You feel compelled to create something on them, but you have no idea what to create.

p: Something to do with cats?

Maybe you should take a walk around the museum. You know, for inspiration.

p: Good idea disembodied voice!

-XKZ

**Comment by funnyboy044** [comment]
p "Hmmm...a few blank easels. Must be for on-site painters."
    p astonished "Woah! What the?"
    p astonished "I feel... {w}something."
    p concerned "Could this be..."
    p astonished "THE GERMINATING SEEDS OF INSPIRATION!?"
    p astonished "I have to create something!"
    p suspicious "But what?"
    "Maybe you should take a walk around the museum. You know, for {color=#ffff00}inspiration.{/color}"
    p happy "Good idea disembodied voice!"
