### ISSUE TITLE
neon lights conversation

### ISSUE THREAD

**Issue by funnyboy044** [pixequil/oso-game-1#307]

**Comment by funnyboy044** [comment]
p "Nothing at the moment."
    nl "Ok..."
    nl "Nothing. Of course. Just like I do every day I stand in front of this stupid stand for 8 stupid hours talking to these stupid-"
    p "Excuse me?"
    nl "...I said as long as you're still browsing, you can talk to Jukebox in the corner and play some music."
    nl "Maybe you'll like one of them enough to purchase one."
    p "Sounds cool. I'll be sure to check it out."

**Comment by funnyboy044** [comment]
neon "Hi again! What do you need?"

**Comment by CONKINGTON** [comment]
```
else:
p "Nothing at the moment."
nl "Ok..."
nl "Nothing. Of course. Just like I do every day I stand in front of this stupid stand for 8 stupid hours talking to these stupid-"
p astonished "Excuse me?"
nl "...I said as long as you're still browsing, you can talk to Jukebox in the corner and play some music."
nl "Maybe you'll like one of them enough to purchase one."
p happy "Sounds cool. I'll be sure to check it out."
```

**Comment by pixequil** [comment]
@funnyboy044

**Comment by funnyboy044** [comment]
This looks good, but I might change p astonished to p concerned
