### ISSUE TITLE
sheet first greeting

### ISSUE THREAD

**Issue by funnyboy044** [pixequil/oso-game-1#309]

**Comment by CONKINGTON** [comment]
sheet (s): Heya welcome to the Music Store, the home for all things audio related.
s: My name is Music Sheet, Sheet for short.
s: Not to brag, but I know every note, rest and staff of music here!
s: Whether you are confused by semidemihemiquavers or looking for recommendations that will take you way back to your childhood, I am the guy for you!
s: Hopefully I'll see you more frequently around here; Neon gets a bit cranky doing nothing after a while.

**Comment by pixequil** [comment]
@funnyboy044
