### ISSUE TITLE
Ahiss the Cat voice

### ISSUE THREAD

**Issue by funnyboy044** [pixequil/oso-game-1#332]

**Comment by CONKINGTON** [comment]
A sophisticated voice for a sophisticated cat!
https://github.com/pixequil/oso-game-1/assets/134235512/01c4a247-07a1-4627-89d8-f6d5fce8d5a9
-XKZ

**Comment by pixequil** [comment]
Where did you get this?

**Comment by CONKINGTON** [comment]
https://commons.wikimedia.org/wiki/File:Alman_Byrd_Fitzw_Metzner2008.ogg

Wikicommons
