### ISSUE TITLE
swap money amounts images?

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#336]
idk, the smaller one looks bigger. thoughts?

**Comment by pixequil** [comment]
actually, it looks like there's been some kind of decision to change it so the cash bundles look different. in that case, the whole money system needs to be redone to consider the multiple different permutations of cash that you can have, instead of it being a growing pile.

**Comment by Loggybears2** [comment]
so kinda like this?
![somethinglikethis](https://github.com/pixequil/oso-game-1/assets/142625846/41392e82-0f99-4497-8b9d-4237d1772bb6)

**Comment by pixequil** [comment]
Red cash shouldn't be included
