### ISSUE TITLE
Posty finds Red Cash on the floor upon entering the blue room.

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#34]
https://github.com/pixequil/oso-game-1/blob/af585882d6f07d821865d6e966c5f748c7852949/game/room004-museum_blue.rpy#L21

**Comment by pixequil** [comment]
https://github.com/pixequil/oso-game-1/blob/c9953ec3e6480bd1dfa989c34c13f39644383997/game/room004-museum_blue.rpy#L26-L35

**Comment by CONKINGTON** [comment]
p: "Alrighty, it appears that Reddy doesn't like green stuff."
p: "Guess I need to go-"
p: "..."
p: "Huh, something red that doesn't grow on trees..."
p: "I think this fits the bill quite nicely."
p: "Red Tile will be so happy with this."
-XKZ

**Comment by funnyboy044** [comment]
> p: "Alrighty, it appears that Reddy doesn't like green stuff." p: "Guess I need to go-" p: "..." p: "Huh, something red that doesn't grow on trees..." p: "I think this fits the bill quite nicely." p: "Red Tile will be so happy with this." -XKZ

Posty says this just as she is entering the room

**Comment by funnyboy044** [comment]
p confused "Huh, what's this red thing doing here?" 
    p confused "Oh well. Yoink."
    show redcash
    $ saw.blue = True
    $ item.red_cash = True
    "You got the {b}{color=#de474e}red cash{/color}{/b}!{p}It\'s money but it\'s red."
    p "I wonder if anyone around here takes red cash."

**Comment by f4nimator** [comment]
changed the emotions since they didn't really fit
```
    scene bg museum_blue
    show posty neutral
    p astonished "Woah. They weren't kidding. This whole exhibit is just blue stuff. My eyes feel like they're-"
    p suspicious "Huh, what's this red thing doing here?" 
    p happy "Oh well. Yoink."
    show redcash
    $ saw.blue = True
    $ item.red_cash = True
    "You got the {b}{color=#de474e}red cash{/color}{/b}!{p}It\'s money but it\'s red."
    p neutral "I wonder if anyone around here takes red cash."
```
