### ISSUE TITLE
initial dolly conversation; transition seamlessly into money checking tree

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#35]
```
    p "meeting dolly first time" # TODO: initial dolly conversation; transition seamlessly into money checking tree
```

https://github.com/pixequil/oso-game-1/blob/40b3ef34aba3e06d0637f7e4e341ca7f6518cc1b/game/money.rpy#L26

**Comment by pixequil** [comment]
https://github.com/pixequil/oso-game-1/blob/c9953ec3e6480bd1dfa989c34c13f39644383997/game/money.rpy#L25-L27

**Comment by pixequil** [comment]
initial dolly conversation; transition seamlessly into money checking tree. Dolly is a Shifty businesswoman with a shoddily built storefront lining the street, and whatever she offers to sell you a “loot box” full of what can surely be wonderful riches, provided you can give her "a lot of money".

**Comment by funnyboy044** [comment]
label .dfirst:
show posty suspicious
p suspicious "What's this?"
dolly "Ah! About time you made it to my stand!"
dolly "I am Dolly, the sole proprietor of this fine establishment."
dolly "How's the delivery going, Posty?"
p happy "It's going fine I suppo-"
p astonished "Wait a minute, how do you know my name?"
dolly "I have connections to your higher-ups, darling."
p confused "Wha-"
dolly "But anyway, what brings you here today?"
p neutral "I guess I'm just browsing." 
dolly "In that case, allow me to offer you something truly exsquisite."
show lootbox at truecenter with moveinbottom
dolly "Behold, a one-of-a-kind, very special, very rare ''loot box.''"
p suspicious "What's in it?"
dolly "Who can say?"
dolly "Perhaps it's filled with wonderful riches to make you exceptionally wealthy!" 
dolly "Or it could be filled with an everyday household object."
dolly "It's all chance, honey! Buy one today and you can win practically anything."
p happy "Alright, you've convinced me! How much?"
dolly "How much do you have?"
$ saw.dolly = True
jump .money_check
