### ISSUE TITLE
repeat dolly conversation; transition seamlessly into money checking tree

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#36]
```
    p "revisiting dolly" # TODO: repeat dolly conversation; transition seamlessly into money checking tree
```

https://github.com/pixequil/oso-game-1/blob/40b3ef34aba3e06d0637f7e4e341ca7f6518cc1b/game/money.rpy#L30

**Comment by pixequil** [comment]
https://github.com/pixequil/oso-game-1/blob/c9953ec3e6480bd1dfa989c34c13f39644383997/game/money.rpy#L29-L31

**Comment by funnyboy044** [comment]
label .drepeat:
    show posty neutral
    p "Hi, Dolly!"
    dolly "Ah, Posty! Rich yet?" # TODO: #36 repeat dolly conversation; transition seamlessly into money checking tree
    show lootbox at truecenter with moveinbottom
    dolly "The random loot box is calling your name!"
    p "Well..."
    jump .money_check
