### ISSUE TITLE
revisiting Blue Tile after you steal the painting

### ISSUE THREAD

**Issue by funnyboy044** [pixequil/oso-game-1#366]
blue tile after the painting is stolen (still doesn't know posty did it)

**Comment by f4nimator** [comment]
kinda short
```
        bluetile "nononononono- AH ma'am have you seen anyone steal the painting that was there?! I NEED to know where it went!!"
        p astonished quiet "{i}Gosh, he's crazy! I almost feel bad. {/i}" #366
        extend neutral quiet "{i}Almost.{/i}"
        p concerned "No, sadly I haven't. Good luck with your search though!"
        bluetile "AUGH!! Where could it have gone?? Who could have taken it?!?"
```

**Comment by funnyboy044** [comment]
Put some of f4nimator's dialogue in what XKZ and I wrote
    
    elif quest.painting_blue:
        show bg museum_blue_p_missing
        show posty concerned
        show bluetile scared
        bluetile "AUGH!! Where could it have gone?? Who could have taken it?!?"
        p "What's wrong? Feeling blue?"
        bluetile "It's the painting of Crayon Box! It's gone!"
        p sad "Oh whaaat? Noooooo! You know where it went?"
        bluetile "I WOULDN'T BE LOOKING AROUND FOR IT IF I KNEW, POSTY!"
        p concerned "Calm down, blue dude! Think about where you last saw it and work backwards from there."
        p "That's what I do when I lose my valuable possessions."
        bluetile annoyed "Ooohh, it's that maroon loser who took my precious painting. That cultural ignoramus was never open to anything that didn't rhyme with zred or mrimson!"
        bluetile  "I was always accommodating to their wishes and desires! I was even considering going to a red exhibit down the street to even it out!"
        bluetile "But that scarlet boor just went and declared war on me! That won't stand on my watch."
        p quiet "{i}Gosh, he's angry! You almost feel bad. {/i}"
        extend quiet "{i}Almost.{/i}"
        p "Um, good luck with your search."
        jump museum_blue
