### ISSUE TITLE
Posty offers the red cash since she lacks real money

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#37]
```
            p "i have red cash" # TODO: Posty offers the red cash since she lacks real money
```

https://github.com/pixequil/oso-game-1/blob/40b3ef34aba3e06d0637f7e4e341ca7f6518cc1b/game/money.rpy#L36

**Comment by pixequil** [comment]
https://github.com/pixequil/oso-game-1/blob/c9953ec3e6480bd1dfa989c34c13f39644383997/game/money.rpy#L35-L38

**Comment by funnyboy044** [comment]
label .money_check:
    if money == 0:
        if item.red_cash:
            show redcash
            p happy "I have some red cash if that will work."
            dolly "Oooh, sorry. There's no market anymore in red dollars."
            show posty concerned
            dolly "How about some real money?"# TODO: #37 Posty offers the red cash since she lacks real money
            p concerned "Sorry, I got nothing."
            dolly "Come back when you have actual cash, Posty."
            hide lootbox
            jump mainstreet
