### ISSUE TITLE
toasty game win conversation

### ISSUE THREAD

**Issue by funnyboy044** [pixequil/oso-game-1#374]
conversation you have with toasty after you deliver the butterflies to crayon box

they have some kind of conversation about how posty actually managed to deliver the package, and how it was quite difficult. posty muses that she could use a nap in the park

**Comment by funnyboy044** [comment]
if win_flag:
        show posty neutral
        show toasty neutral
        t "you won; no need to have a hint" # they have some kind of conversation about how posty actually managed to deliver the package, and how it was quite difficult. posty muses that she could use a nap in the park
        return

**Comment by pixequil** [comment]
assigned to AnArtichoke_
