### ISSUE TITLE
posty has no money

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#38]
```
            p "i have nothing" # todo: posty has no money
```

https://github.com/pixequil/oso-game-1/blob/40b3ef34aba3e06d0637f7e4e341ca7f6518cc1b/game/money.rpy#L39

**Comment by pixequil** [comment]
https://github.com/pixequil/oso-game-1/blob/c9953ec3e6480bd1dfa989c34c13f39644383997/game/money.rpy#L39-L41

**Comment by funnyboy044** [comment]
p concerned "Ooh, uh, I'm afraid I don't have any money."
            p concerned "Can we barter?"
            dolly "No."
            dolly "Come back when you have a penny to your name, Posty." # todo: #38 posty has no 
            hide lootbox
            jump mainstreet
