### ISSUE TITLE
posty has "some" money

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#39]
```
        p "i have some money" # todo: posty has "some" money
```

https://github.com/pixequil/oso-game-1/blob/40b3ef34aba3e06d0637f7e4e341ca7f6518cc1b/game/money.rpy#L41

**Comment by pixequil** [comment]
https://github.com/pixequil/oso-game-1/blob/c9953ec3e6480bd1dfa989c34c13f39644383997/game/money.rpy#L42-L45

**Comment by pixequil** [comment]
posty has "some" money. this is not enough money for Dolly; Dolly wants "a lot of" money.

**Comment by funnyboy044** [comment]
show cash_bundle_1 at truecenter
        p happy "I have some money. Is this enough for anything?" # todo: #39 posty has "some" money. 
        dolly "Only my pocket lint."
        dolly "I want A LOT of money, Posty. Double what you have now."
        p happy "Ok, I'll be back later." #this is not enough money for Dolly; Dolly wants "a lot of" money.
        jump mainstreet
