### ISSUE TITLE
hint for if you have the imaginary lighter and havent talked to ahiss

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#407]

**Comment by pixequil** [comment]
assigned to Paramailk

**Comment by Paramilky** [comment]
doing it [insert thumbs up emoji here]

*ps you may have mispelt my name

**Comment by pixequil** [comment]
i copy pasted it from the form. regardless, thank you for the correction

**Comment by Paramilky** [comment]
oops... my fault 😅
