### ISSUE TITLE
ladle, empty and filled with soup versions

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#41]
```
    show ladle_empty # TODO: ladle, empty and filled with soup versions
```

https://github.com/pixequil/oso-game-1/blob/4a7f7a45ae16f5ff6c209df539b1f7a2bfad9690/game/room004-museum_blue.rpy#L44

**Comment by pixequil** [comment]
https://github.com/pixequil/oso-game-1/blob/c9953ec3e6480bd1dfa989c34c13f39644383997/game/room004-museum_blue.rpy#L47

**Comment by funnyboy044** [comment]
**ASSETS:**
Empty Ladle: https://drive.google.com/file/d/12HNz0fWmfY0MpCPaF0VzGgX2y14L6l_q/view?usp=drive_link
Full Ladle: https://drive.google.com/file/d/1oes5KtiSq3ItErvIwlGqwHl0vt5tiFQ-/view?usp=drive_link

**Comment by funnyboy044** [comment]
Credits go to Faye's_odd.5450 (that's how they want to be credited)

**Comment by pixequil** [comment]
needs implementing

**Comment by funnyboy044** [comment]
> **ASSETS:** Empty Ladle: https://drive.google.com/file/d/12HNz0fWmfY0MpCPaF0VzGgX2y14L6l_q/view?usp=drive_link Full Ladle: https://drive.google.com/file/d/1oes5KtiSq3ItErvIwlGqwHl0vt5tiFQ-/view?usp=drive_link

btw these assets are 500 x 500 px, there's another version that's 70 x 70 in the google drive, but they're a little blurry. I don't know if it'd be better to resize them in the engine.
