### ISSUE TITLE
describe red cash

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#42]
```
    "You got the {b}{color=#de474e}red cash{/color}{/b}!" # todo: describe red cash
```

https://github.com/pixequil/oso-game-1/blob/4a7f7a45ae16f5ff6c209df539b1f7a2bfad9690/game/room004-museum_blue.rpy#L34

**Comment by pixequil** [comment]
https://github.com/pixequil/oso-game-1/blob/c9953ec3e6480bd1dfa989c34c13f39644383997/game/room004-museum_blue.rpy#L34

**Comment by PenTick** [comment]
It’s money but it’s red.

**Comment by pixequil** [comment]
@PenTick what do you want to be credited as? it can't be added until we know what you want to be known as in the credits.

**Comment by PenTick** [comment]
Compital
