### ISSUE TITLE
short conversation with red tile

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#44]
```
        p "_" # todo: short conversation with red tile
```

https://github.com/pixequil/oso-game-1/blob/4a7f7a45ae16f5ff6c209df539b1f7a2bfad9690/game/room004-museum_blue.rpy#L51

**Comment by pixequil** [comment]
https://github.com/pixequil/oso-game-1/blob/c9953ec3e6480bd1dfa989c34c13f39644383997/game/room004-museum_blue.rpy#L52-L54

**Comment by f4nimator** [comment]
posty didnt attempt to spill the soup yet

**Comment by funnyboy044** [comment]
p "Hey, Red Tile."
        redtile "Just call me Red. Have you gotten rid of that ladle yet?"
        p "No, but I should be able to keep it a secret as long as I've got it hidden."
        redtile "Ok, well be careful. I don't want the security guard or Blue figuring out I tried to vandalize this painting."
        redtile "Even though it deserves it. It's a mockery to the medium itself!"
        redtile "Even a small trace of dark red would create a more appealing contrast than just light blue and dark blue."
        p "You know, if I wanted to, I could do what you did again and take the painting for myself."
        p astonished "I really want that painting. It sings to me..."
        redtile "You're not saying you're gonna risk your own life to deface an art piece, are you?"
        p "No..."
        p "And on that note, I need to go."
