### ISSUE TITLE
Miso Soup talksprite

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#45]
```
    show miso # TODO: Miso Soup talksprite
```

https://github.com/pixequil/oso-game-1/blob/bd57125f5e4dec18dccc18f1065b87bc6e26e7df/game/room001-mainstreet.rpy#L155

**Comment by pixequil** [comment]
https://github.com/pixequil/oso-game-1/blob/c9953ec3e6480bd1dfa989c34c13f39644383997/game/room001-mainstreet.rpy#L155

**Comment by pixequil** [comment]
Miso Soup - A bowl of Miso Soup sitting on the sidewalk right by the Art Museum entrance, looking super down. They’re holding a plastic wrap in one hand. If you talk to them they’ll tell you about how they got kicked out of the museum and got a notice of reprimand for spilling soup in one of the gates protecting the paintings. They swore they didn’t do it but got kicked out anyway, and upon learning this, their family of Elite Art Connoisseurs kicked them out.

**Comment by CONKINGTON** [comment]
![miso_close](https://github.com/pixequil/oso-game-1/assets/134235512/73ebd280-9b16-4da5-a2d8-c47eacad17ba)
![miso_open](https://github.com/pixequil/oso-game-1/assets/134235512/3637b2be-293c-40a3-a4f9-d1e3f976a8c4)

**Comment by pixequil** [comment]
@funnyboy044 did you assign this? just checking since it doesn't match up with the spreadsheet

**Comment by funnyboy044** [comment]
no i did not

**Comment by pixequil** [comment]
@CONKINGTON (cc @Martysh12 jic) now that we've opened the game project up to the community as a whole, i think for the sake of giving everyone a chance to contribute, we shouldn't have people producing art without being asked to. this is how it's worked for the rest of OSO so far, anyway.

as for writing tasks... discussing that on the OSO discord.

**Comment by CONKINGTON** [comment]
Apologies for jumping the gun.

**Comment by funnyboy044** [comment]
I'm gonna wait until #79 is done before I assign this, it'll be easier for the person to make this when they have a character reference.

**Comment by pixequil** [comment]
sounds like a plan
