### ISSUE TITLE
miso soup conversation before youve taken any soup

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#46]
```
        p "_" # TODO: miso soup conversation before youve taken any soup
```

https://github.com/pixequil/oso-game-1/blob/57fca353785c1616325e3e364c9c8086f3313ba8/game/room001-mainstreet.rpy#L158

**Comment by pixequil** [comment]
https://github.com/pixequil/oso-game-1/blob/c9953ec3e6480bd1dfa989c34c13f39644383997/game/room001-mainstreet.rpy#L157-L160

**Comment by funnyboy044** [comment]
show posty neutral
        p "Hello!"
        miso " {i}Ohhh, my family is gonna kill me... {/i}"
        p concerned "Is there a problem?"
        miso "Huh? Oh hi, didn't see you there!"
        miso "You betcha there's a problem! I just got banned from the musuem!"
        miso "The security guard in there said I spilled my soup on one of the security gates and almost ruined one of the paintings!"
        miso "But I didn't do it! I always bring plastic wrap to protect the soup from spilling! Honest!"
        miso "I tried telling him I didn't do it, but he wrote me a notice of reprimand anyway and kicked me out! That guy is so strict!"
        p "Dang, that sucks..."
        miso "Oh, it gets worse!"
        miso "My parents are really big art connoisseurs! If they find out that I could've destroyed something priceless, they might kick me out of their fortune!"
        p "I'm sorry, there's nothing I can really do to help right now."
        p "If I can find a way to make it up, I'll let you know."
        miso "Thanks for trying, I guess."

**Comment by pixequil** [comment]
maybe throw in a line after the notice of reprimand part thats  like "some guy in an alley came up to me and told me i was cool for having the notice of reprimand! i dont want weird guys from alleys to think im cool!" except worded better

**Comment by f4nimator** [comment]
slightly edited it to add a line about the notice of reprimand
```
    elif (item.ladle_empty == False) and (miso_took == False):
        show posty neutral
        p happy "Hello!"
        miso " {i}Ohhh, my family is gonna kill me... {/i}"
        p concerned "Is there a problem?"
        miso "Huh? Oh hi, didn't see you there!"
        miso "You betcha there's a problem! I just got banned from the musuem!"
        miso "The security guard in there said I spilled my soup on one of the security gates and almost ruined one of the paintings!"
        miso "But I didn't do it! I always bring plastic wrap to protect the soup from spilling! Honest!"
        miso "I tried telling him I didn't do it, but he wrote me a notice of reprimand anyway and kicked me out! That guy is so strict!"
        p "Dang, that sucks..."
        miso "Oh, it gets worse!"
        miso "My parents are really big art connoisseurs! If they find out that I could've destroyed something priceless, they might kick me out of their fortune!"
        miso "This guy in an alley even told me I was cool for having the notice of reprimand!"
        miso "I dont want weird guys from alleys to think I'm cool!!"
        p "I'm sorry, there's nothing I can really do to help right now."
        p "If I can find a way to make it up, I'll let you know."
        miso "Thanks for trying, I guess."
```
