### ISSUE TITLE
you take soup from Miso Soup

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#47]
```
        p "_" # TODO: you take soup from Miso Soup 
```

https://github.com/pixequil/oso-game-1/blob/57fca353785c1616325e3e364c9c8086f3313ba8/game/room001-mainstreet.rpy#L163

**Comment by pixequil** [comment]
https://github.com/pixequil/oso-game-1/blob/c9953ec3e6480bd1dfa989c34c13f39644383997/game/room001-mainstreet.rpy#L162-L171

**Comment by xbeo01** [comment]
```
 elif item_ladle_empty and (miso_took == False): 
     p "Hey, do you mind if I just-"
     miso "What are you about to do?"
     # add animation where posty moves towards miso to get the soup, plays right after miso's text, as if interrupting -xbeo
     $ item_ladle_empty = False 
     $ item_ladle_full = True 
     $ miso_took = True 
     show ladle_full 
     "You filled the {b}ladle{/b} with {b}miso soup{/b}! It consists of soybeans, sea salt and rice."
     # update description in inventory aswell -xbeo
     miso "Hey! Not you too..."
     jump mainstreet 
```

**Comment by pixequil** [comment]
#48 remember to add xbeo to the credits for both dialogue and item descriptions

**Comment by pixequil** [comment]
don't use the item description here; someone else submitted a more suitable one in #48

**Comment by pixequil** [comment]
also: the outline depicts miso as unaware of who took the soup last time, so, i think the last line of this could use revision

**Comment by funnyboy044** [comment]
Using the item description from #48 and Loggybears submission (on discord)

        show posty sad
        p sad "I'm so sorry for this." 
        miso "What are you about t-"
        $ item.ladle_empty = False
        $ item.ladle_full = True
        $ miso_took = True
        show ladle_full
        "You filled the {b}ladle{/b} with {b}miso soup{/b}!"
        "Filled with miso soup, hell to clean up properly. Perfect sabotage."
        miso "My soup!"
        jump mainstreet

**Comment by Loggybears2** [comment]
My soup!
