### ISSUE TITLE
describe soup-filled ladle

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#48]
```
        "You filled the {b}ladle{/b} with {b}miso soup{/b}!" # TODO: describe soup-filled ladle
```

https://github.com/pixequil/oso-game-1/blob/57fca353785c1616325e3e364c9c8086f3313ba8/game/room001-mainstreet.rpy#L168

**Comment by pixequil** [comment]
https://github.com/pixequil/oso-game-1/blob/c9953ec3e6480bd1dfa989c34c13f39644383997/game/room001-mainstreet.rpy#L169

**Comment by PenTick** [comment]
It’s a soup ladle. The soup’s tomato.

**Comment by pixequil** [comment]
the soup is miso.

**Comment by pixequil** [comment]
@PenTick i suggest reviewing the pinned outline google doc when writing item descriptions

**Comment by PenTick** [comment]
Nope yeah, it’s miso. Sorry.

**Comment by CONKINGTON** [comment]
Filled with miso soup,
hell to clean up properly.
Perfect sabotage.

**Comment by funnyboy044** [comment]
A haiku!

> Filled with miso soup, hell to clean up properly. Perfect sabotage.
