### ISSUE TITLE
miso soup conversation after you've taken soup

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#49]
```
        p "_" #TODO: miso soup conversation after you've taken soup
```

https://github.com/pixequil/oso-game-1/blob/c9953ec3e6480bd1dfa989c34c13f39644383997/game/room001-mainstreet.rpy#L173-L176

**Comment by funnyboy044** [comment]
show posty neutral
        p sad "Again, I'm so sorry for taking some of your soup."
        miso "What did you even do that for?"
        p concerned "I need it for something. It's kind of hard to explain right now."
        p "I'll make it up to you when I finish what I have to do!"
        miso "I sure hope so! This has been the weirdest day ever!"
        jump mainstreet
