### ISSUE TITLE
empty ladle hint (use it on miso soup)

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#52]
```
        t "hint for if you have empty ladle" # todo: empty ladle hint (use it on miso soup)
```

https://github.com/pixequil/oso-game-1/blob/c9953ec3e6480bd1dfa989c34c13f39644383997/game/toasty_hints.rpy#L28

**Comment by CONKINGTON** [comment]
"This ladle seems rather empty; maybe you should fill it up with something."

**Comment by pixequil** [comment]
hints are conversations with toasty. you can look in the toasty_hints script file for an example

**Comment by CONKINGTON** [comment]
t " What are you doing with that?"
p "Dunno. A red guy gave it to me."
t "..."
p "What?"
t "This ladle seems rather empty: maybe you should fill it up with something, dumbass."
p "That was very rude."
