### ISSUE TITLE
talking to B.T. Net (does not progress the plot)

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#53]
```
        p "_" # TODO: talking to B.T. Net (does not progress the plot)
```

https://github.com/pixequil/oso-game-1/blob/f472c3023627f967baea7fc81cef5df71461bcd5/game/room001-mainstreet.rpy#L195-L199

**Comment by funnyboy044** [comment]
show posty happy
        p happy "Hello again!"
        btnet "How's your progress on the delievery?"
        p concerned "I ran into a few slip-ups, but I think I can handle it!"
        btnet "If it's too difficult for you, I can always pass it on to someone else, like your friend Toasty or-"
        p astonished "No it's ok! I've got it!"
        p "I'll let you know when it's delivered!"
        btnet "Ok Posty, good luck!"

**Comment by pixequil** [comment]
we should either modify this so it still makes sense if you just finished the initial bt net conversation, or have it become conditional upon something
