### ISSUE TITLE
talking to B.T. Net after a successful delivery! (game is in win state)

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#54]
```
        p "_" # TODO: talking to B.T. Net after a successful delivery! (game is in win state)
```

https://github.com/pixequil/oso-game-1/blob/c9953ec3e6480bd1dfa989c34c13f39644383997/game/room001-mainstreet.rpy#L196

**Comment by funnyboy044** [comment]
p happy "I delievered the package! Crayon Box was impressed with the butterflies!"
        btnet "Excellent work, Posty! I knew you could do it!"
        p happy "Do you need me to deliever any other packagaes today?"
        btnet "Nah. I don't want to overwork you, especially after this important order for OSO!"
        btnet "Go take a nap! You've earned it!"
        p happy "Thanks B.T.! Talk to you later!"
