### ISSUE TITLE
Resize posty sprites

### ISSUE THREAD

**Issue by Martysh12** [pixequil/oso-game-1#66]
Posty's sprites look horrible when scaled, which means they need to be scaled before being shown.
~~Instead of doing that manually, a script can be written which reads a registry of sprites, and scales them accordingly.
There also need to be instructions on how to add sprites to the registry.~~

EDIT: All sprites will be scaled manually

**Comment by pixequil** [comment]
- [ ] scale up posty sprites 200%
- [ ] remove zoom functions from her sprite calls
