### ISSUE TITLE
Miso Soup mini sprite

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#79]
a mini sprite for Miso Soup, to be used in a navigation imagemap.

**Comment by funnyboy044** [comment]
Asset: https://drive.google.com/file/d/1xijegnHKg_eV82wMTtgpjI2QQ0bj2UjW/view?usp=sharing
Credit: SilverSpewer
![miso_soup_ow](https://github.com/pixequil/oso-game-1/assets/63936011/e2e9dfc4-57be-4087-9213-e2509ae26f07)
