### ISSUE TITLE
arrows for the main street imagemap

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#81]
- [x] northward arrow for the alley
- [x] rightward arrow for the dome
- [x] southward arrow for the park

**Comment by funnyboy044** [comment]
how big in px should the arrows be?

**Comment by pixequil** [comment]
Any

**Comment by funnyboy044** [comment]
![arrow_up](https://github.com/pixequil/oso-game-1/assets/63936011/df254120-3906-4f16-b77e-ad2ab787b410)
![arrow_down](https://github.com/pixequil/oso-game-1/assets/63936011/91e6adf5-3f2a-40bb-8a4a-5090e0b69779)
![arrow_right](https://github.com/pixequil/oso-game-1/assets/63936011/79196314-3ac4-47f5-bc2b-529a692b727f)

**Comment by funnyboy044** [comment]
arrow assets
