### ISSUE TITLE
arrow for leaving the dome with

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#82]
left-pointing arrow for returning to main street from the dome. for in an imagemap

**Comment by funnyboy044** [comment]
![arrow_left](https://github.com/pixequil/oso-game-1/assets/63936011/e41bcb8e-559a-4823-afaa-e6a0fbc8edfc)

**Comment by funnyboy044** [comment]
![arrow_right](https://github.com/pixequil/oso-game-1/assets/63936011/0821ec13-33b2-4b56-b27f-8a28e604e0a3)

**Comment by pixequil** [comment]
@funnyboy044 who drew this?

**Comment by funnyboy044** [comment]
> @funnyboy044 who drew this?

me, it's the same arrow from the mainstreet maps, i figured we can reuse them through the whole game

**Comment by pixequil** [comment]
I think it would be nice to have a variety; arrows are fun to draw since anyone can make them, and this also prevents us from being stuck with one style of arrows
