### ISSUE TITLE
implement security cameron talksprite

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#84]
it's pretty big! but it doesn't need animation, so it should be just like BT Net.

**Comment by Martysh12** [comment]
on it

**Comment by Martysh12** [comment]
well of course as soon as there are talksprites available

**Comment by pixequil** [comment]
https://github.com/pixequil/oso-game-1/blob/22f1f039773f72710f28984184f51637f40ba406/game/images/talksprites/Security_Cameron.png

**Comment by pixequil** [comment]
feel free to rename the file if you think the capitalization is a problem (it does sort of stand out, and it makes a mess in asciibetical things)
